from enum import StrEnum


class Icon(StrEnum):
    """Lucide icon slugs supported by LongLink runtimes."""

    activity = "activity"
    arrow_right = "arrow-right"
    banknote = "banknote"
    bell = "bell"
    box = "box"
    boxes = "boxes"
    building_2 = "building-2"
    check = "check"
    clipboard_list = "clipboard-list"
    container = "container"
    cpu = "cpu"
    database = "database"
    download = "download"
    hard_drive = "hard-drive"
    layers = "layers"
    layout_dashboard = "layout-dashboard"
    layout_grid = "layout-grid"
    link = "link"
    list = "list"
    list_check = "list-check"
    map_pin = "map-pin"
    plus = "plus"
    rocket = "rocket"
    rotate_ccw = "rotate-ccw"
    settings_2 = "settings-2"
    shield_check = "shield-check"
    sliders_horizontal = "sliders-horizontal"
    timer = "timer"
    users = "users"
    x = "x"
