import type { ComponentType } from 'react';
import {
    Action,
    Avatar,
    Badge,
    Button,
    Card,
    CheckboxInput,
    Dialog,
    Divider,
    FileInput,
    FormLayout,
    Grid,
    Heading,
    Icon,
    Link,
    NumberInput,
    RadioList,
    RadioListItem,
    Selector,
    SelectorOption,
    SideNav,
    SideNavItem,
    Slider,
    Stack,
    Switch,
    Tab,
    TabList,
    Table,
    TableColumn,
    Text,
    TextArea,
    TextInput,
} from '../adapters';
import type { Props } from '../types';

/** Explicit Astryx 0.3 XML tag-to-adapter registry. */
export const xmlComponentRegistry: Record<string, ComponentType<Props>> = {
    Action,
    Avatar,
    Badge,
    Button,
    Card,
    CheckboxInput,
    Dialog,
    Divider,
    FileInput,
    FormLayout,
    Grid,
    Heading,
    Icon,
    Link,
    NumberInput,
    RadioList,
    RadioListItem,
    Selector,
    SelectorOption,
    SideNav,
    SideNavItem,
    Slider,
    Stack,
    Switch,
    Tab,
    TabList,
    Table,
    TableColumn,
    Text,
    TextArea,
    TextInput,
};
