apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - common.yml
    - operator.yml
patches:
    - target:
          kind: ConfigMap
          name: rook-ceph-operator-config
      patch: |-
          - op: add
            path: /data/ROOK_USE_CSI_OPERATOR
            value: "false"
          - op: add
            path: /data/ROOK_CSI_DISABLE_DRIVER
            value: "true"
          - op: add
            path: /data/ROOK_CSI_ENABLE_RBD
            value: "false"
          - op: add
            path: /data/ROOK_CSI_ENABLE_CEPHFS
            value: "false"
          - op: add
            path: /data/ROOK_CEPH_ALLOW_LOOP_DEVICES
            value: "false"
          - op: add
            path: /data/ROOK_OBC_ALLOW_ADDITIONAL_CONFIG_FIELDS
            value: bucketMaxSize,bucketMaxObjects
