import os

os.environ["DEV"] = "true"
os.environ["ENV_DATABASE_URL"] = "sqlite+aiosqlite:///./dev.db"
os.environ["ENV_OIDC_REDIRECT_URI"] = "http://localhost:8000/auth/oidc"
os.environ["ENV_OIDC_SCOPES"] = "openid profile email"
os.environ["ENV_PROVISION_DATABASE_HOST"] = "localhost"
os.environ["ENV_PROVISION_DATABASE_PORT"] = "5432"
os.environ["ENV_PROVISION_DATABASE_USERNAME"] = "admin"
os.environ["ENV_PROVISION_DATABASE_PASSWORD"] = "admin"
os.environ["ENV_PROVISION_DATABASE_MAINTENANCE_DATABASE"] = "postgres"
os.environ["ENV_PROVISION_STORAGE_ENDPOINT_URL"] = "http://localhost:9000"
os.environ["ENV_PROVISION_STORAGE_ACCESS_KEY_ID"] = "admin"
os.environ["ENV_PROVISION_STORAGE_SECRET_ACCESS_KEY"] = "admin"
os.environ["ENV_PROVISION_COMPUTE_KUBE_API_SERVER"] = "https://localhost:8001"
os.environ["ENV_PROVISION_COMPUTE_KUBE_CONFIG_PATH"] = "/app/kubeconfig"
os.environ["ENV_PROVISION_COMPUTE_NAMESPACE"] = "default"
os.environ["ENV_PROVISION_COMPUTE_VERIFY_SSL"] = "false"
os.environ["URL"] = "http://localhost:5173"
os.environ["KEY"] = "test-secret"
