version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directories:
      - "/api"
      - "/sdk"
      - "/org"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/dev"
    schedule:
      interval: "weekly"
