changelog:
    categories:
        - title: API
          labels:
              - api
        - title: SDK
          labels:
              - sdk
        - title: Web
          labels:
              - web
        - title: Other Changes
          labels:
              - '*'
