import enum


# https://www.iban.com/country-codes
class CountryCode(str, enum.Enum):
    """ISO 3166-1 alpha-2 country codes."""

    AD = "AD"  # Andorra
    AE = "AE"  # United Arab Emirates
    AF = "AF"  # Afghanistan
    AG = "AG"  # Antigua and Barbuda
    AI = "AI"  # Anguilla
    AL = "AL"  # Albania
    AM = "AM"  # Armenia
    AO = "AO"  # Angola
    AQ = "AQ"  # Antarctica
    AR = "AR"  # Argentina
    AS = "AS"  # American Samoa
    AT = "AT"  # Austria
    AU = "AU"  # Australia
    AW = "AW"  # Aruba
    AX = "AX"  # Åland Islands
    AZ = "AZ"  # Azerbaijan
    BA = "BA"  # Bosnia and Herzegovina
    BB = "BB"  # Barbados
    BD = "BD"  # Bangladesh
    BE = "BE"  # Belgium
    BF = "BF"  # Burkina Faso
    BG = "BG"  # Bulgaria
    BH = "BH"  # Bahrain
    BI = "BI"  # Burundi
    BJ = "BJ"  # Benin
    BL = "BL"  # Saint Barthélemy
    BM = "BM"  # Bermuda
    BN = "BN"  # Brunei Darussalam
    BO = "BO"  # Bolivia
    BQ = "BQ"  # Bonaire, Sint Eustatius and Saba
    BR = "BR"  # Brazil
    BS = "BS"  # Bahamas
    BT = "BT"  # Bhutan
    BV = "BV"  # Bouvet Island
    BW = "BW"  # Botswana
    BY = "BY"  # Belarus
    BZ = "BZ"  # Belize
    CA = "CA"  # Canada
    CC = "CC"  # Cocos (Keeling) Islands
    CD = "CD"  # Congo (Democratic Republic)
    CF = "CF"  # Central African Republic
    CG = "CG"  # Congo
    CH = "CH"  # Switzerland
    CI = "CI"  # Côte d'Ivoire
    CK = "CK"  # Cook Islands
    CL = "CL"  # Chile
    CM = "CM"  # Cameroon
    CN = "CN"  # China
    CO = "CO"  # Colombia
    CR = "CR"  # Costa Rica
    CU = "CU"  # Cuba
    CV = "CV"  # Cabo Verde
    CW = "CW"  # Curaçao
    CX = "CX"  # Christmas Island
    CY = "CY"  # Cyprus
    CZ = "CZ"  # Czechia
    DE = "DE"  # Germany
    DJ = "DJ"  # Djibouti
    DK = "DK"  # Denmark
    DM = "DM"  # Dominica
    DO = "DO"  # Dominican Republic
    DZ = "DZ"  # Algeria
    EC = "EC"  # Ecuador
    EE = "EE"  # Estonia
    EG = "EG"  # Egypt
    EH = "EH"  # Western Sahara
    ER = "ER"  # Eritrea
    ES = "ES"  # Spain
    ET = "ET"  # Ethiopia
    FI = "FI"  # Finland
    FJ = "FJ"  # Fiji
    FK = "FK"  # Falkland Islands
    FM = "FM"  # Micronesia
    FO = "FO"  # Faroe Islands
    FR = "FR"  # France
    GA = "GA"  # Gabon
    GB = "GB"  # United Kingdom
    GD = "GD"  # Grenada
    GE = "GE"  # Georgia
    GF = "GF"  # French Guiana
    GG = "GG"  # Guernsey
    GH = "GH"  # Ghana
    GI = "GI"  # Gibraltar
    GL = "GL"  # Greenland
    GM = "GM"  # Gambia
    GN = "GN"  # Guinea
    GP = "GP"  # Guadeloupe
    GQ = "GQ"  # Equatorial Guinea
    GR = "GR"  # Greece
    GS = "GS"  # South Georgia and the South Sandwich Islands
    GT = "GT"  # Guatemala
    GU = "GU"  # Guam
    GW = "GW"  # Guinea-Bissau
    GY = "GY"  # Guyana
    HK = "HK"  # Hong Kong
    HM = "HM"  # Heard Island and McDonald Islands
    HN = "HN"  # Honduras
    HR = "HR"  # Croatia
    HT = "HT"  # Haiti
    HU = "HU"  # Hungary
    ID = "ID"  # Indonesia
    IE = "IE"  # Ireland
    IL = "IL"  # Israel
    IM = "IM"  # Isle of Man
    IN = "IN"  # India
    IO = "IO"  # British Indian Ocean Territory
    IQ = "IQ"  # Iraq
    IR = "IR"  # Iran
    IS = "IS"  # Iceland
    IT = "IT"  # Italy
    JE = "JE"  # Jersey
    JM = "JM"  # Jamaica
    JO = "JO"  # Jordan
    JP = "JP"  # Japan
    KE = "KE"  # Kenya
    KG = "KG"  # Kyrgyzstan
    KH = "KH"  # Cambodia
    KI = "KI"  # Kiribati
    KM = "KM"  # Comoros
    KN = "KN"  # Saint Kitts and Nevis
    KP = "KP"  # North Korea
    KR = "KR"  # South Korea
    KW = "KW"  # Kuwait
    KY = "KY"  # Cayman Islands
    KZ = "KZ"  # Kazakhstan
    LA = "LA"  # Laos
    LB = "LB"  # Lebanon
    LC = "LC"  # Saint Lucia
    LI = "LI"  # Liechtenstein
    LK = "LK"  # Sri Lanka
    LR = "LR"  # Liberia
    LS = "LS"  # Lesotho
    LT = "LT"  # Lithuania
    LU = "LU"  # Luxembourg
    LV = "LV"  # Latvia
    LY = "LY"  # Libya
    MA = "MA"  # Morocco
    MC = "MC"  # Monaco
    MD = "MD"  # Moldova
    ME = "ME"  # Montenegro
    MF = "MF"  # Saint Martin
    MG = "MG"  # Madagascar
    MH = "MH"  # Marshall Islands
    MK = "MK"  # North Macedonia
    ML = "ML"  # Mali
    MM = "MM"  # Myanmar
    MN = "MN"  # Mongolia
    MO = "MO"  # Macao
    MP = "MP"  # Northern Mariana Islands
    MQ = "MQ"  # Martinique
    MR = "MR"  # Mauritania
    MS = "MS"  # Montserrat
    MT = "MT"  # Malta
    MU = "MU"  # Mauritius
    MV = "MV"  # Maldives
    MW = "MW"  # Malawi
    MX = "MX"  # Mexico
    MY = "MY"  # Malaysia
    MZ = "MZ"  # Mozambique
    NA = "NA"  # Namibia
    NC = "NC"  # New Caledonia
    NE = "NE"  # Niger
    NF = "NF"  # Norfolk Island
    NG = "NG"  # Nigeria
    NI = "NI"  # Nicaragua
    NL = "NL"  # Netherlands
    NO = "NO"  # Norway
    NP = "NP"  # Nepal
    NR = "NR"  # Nauru
    NU = "NU"  # Niue
    NZ = "NZ"  # New Zealand
    OM = "OM"  # Oman
    PA = "PA"  # Panama
    PE = "PE"  # Peru
    PF = "PF"  # French Polynesia
    PG = "PG"  # Papua New Guinea
    PH = "PH"  # Philippines
    PK = "PK"  # Pakistan
    PL = "PL"  # Poland
    PM = "PM"  # Saint Pierre and Miquelon
    PN = "PN"  # Pitcairn
    PR = "PR"  # Puerto Rico
    PS = "PS"  # Palestine
    PT = "PT"  # Portugal
    PW = "PW"  # Palau
    PY = "PY"  # Paraguay
    QA = "QA"  # Qatar
    RE = "RE"  # Réunion
    RO = "RO"  # Romania
    RS = "RS"  # Serbia
    RU = "RU"  # Russia
    RW = "RW"  # Rwanda
    SA = "SA"  # Saudi Arabia
    SB = "SB"  # Solomon Islands
    SC = "SC"  # Seychelles
    SD = "SD"  # Sudan
    SE = "SE"  # Sweden
    SG = "SG"  # Singapore
    SH = "SH"  # Saint Helena
    SI = "SI"  # Slovenia
    SJ = "SJ"  # Svalbard and Jan Mayen
    SK = "SK"  # Slovakia
    SL = "SL"  # Sierra Leone
    SM = "SM"  # San Marino
    SN = "SN"  # Senegal
    SO = "SO"  # Somalia
    SR = "SR"  # Suriname
    SS = "SS"  # South Sudan
    ST = "ST"  # Sao Tome and Principe
    SV = "SV"  # El Salvador
    SX = "SX"  # Sint Maarten
    SY = "SY"  # Syria
    SZ = "SZ"  # Eswatini
    TC = "TC"  # Turks and Caicos Islands
    TD = "TD"  # Chad
    TF = "TF"  # French Southern Territories
    TG = "TG"  # Togo
    TH = "TH"  # Thailand
    TJ = "TJ"  # Tajikistan
    TK = "TK"  # Tokelau
    TL = "TL"  # Timor-Leste
    TM = "TM"  # Turkmenistan
    TN = "TN"  # Tunisia
    TO = "TO"  # Tonga
    TR = "TR"  # Turkey
    TT = "TT"  # Trinidad and Tobago
    TV = "TV"  # Tuvalu
    TW = "TW"  # Taiwan
    TZ = "TZ"  # Tanzania
    UA = "UA"  # Ukraine
    UG = "UG"  # Uganda
    UM = "UM"  # United States Minor Outlying Islands
    US = "US"  # United States of America
    UY = "UY"  # Uruguay
    UZ = "UZ"  # Uzbekistan
    VA = "VA"  # Holy See
    VC = "VC"  # Saint Vincent and the Grenadines
    VE = "VE"  # Venezuela
    VG = "VG"  # British Virgin Islands
    VI = "VI"  # U.S. Virgin Islands
    VN = "VN"  # Viet Nam
    VU = "VU"  # Vanuatu
    WF = "WF"  # Wallis and Futuna
    WS = "WS"  # Samoa
    YE = "YE"  # Yemen
    YT = "YT"  # Mayotte
    ZA = "ZA"  # South Africa
    ZM = "ZM"  # Zambia
    ZW = "ZW"  # Zimbabwe


class CountryNames(str, enum.Enum):
    """ISO 3166-1 alpha-2 country codes."""
    AD = "Andorra"
    AE = "United Arab Emirates"
    AF = "Afghanistan"
    AG = "Antigua and Barbuda"
    AI = "Anguilla"
    AL = "Albania"
    AM = "Armenia"
    AO = "Angola"
    AQ = "Antarctica"
    AR = "Argentina"
    AS = "American Samoa"
    AT = "Austria"
    AU = "Australia"
    AW = "Aruba"
    AX = "Åland Islands"
    AZ = "Azerbaijan"
    BA = "Bosnia and Herzegovina"
    BB = "Barbados"
    BD = "Bangladesh"
    BE = "Belgium"
    BF = "Burkina Faso"
    BG = "Bulgaria"
    BH = "Bahrain"
    BI = "Burundi"
    BJ = "Benin"
    BL = "Saint Barthélemy"
    BM = "Bermuda"
    BN = "Brunei Darussalam"
    BO = "Bolivia"
    BQ = "Bonaire, Sint Eustatius and Saba"
    BR = "Brazil"
    BS = "Bahamas"
    BT = "Bhutan"
    BV = "Bouvet Island"
    BW = "Botswana"
    BY = "Belarus"
    BZ = "Belize"
    CA = "Canada"
    CC = "Cocos (Keeling) Islands"
    CD = "Congo (Democratic Republic)"
    CF = "Central African Republic"
    CG = "Congo"
    CH = "Switzerland"
    CI = "Côte d'Ivoire"
    CK = "Cook Islands"
    CL = "Chile"
    CM = "Cameroon"
    CN = "China"
    CO = "Colombia"
    CR = "Costa Rica"
    CU = "Cuba"
    CV = "Cabo Verde"
    CW = "Curaçao"
    CX = "Christmas Island"
    CY = "Cyprus"
    CZ = "Czechia"
    DE = "Germany"
    DJ = "Djibouti"
    DK = "Denmark"
    DM = "Dominica"
    DO = "Dominican Republic"
    DZ = "Algeria"
    EC = "Ecuador"
    EE = "Estonia"
    EG = "Egypt"
    EH = "Western Sahara"
    ER = "Eritrea"
    ES = "Spain"
    ET = "Ethiopia"
    FI = "Finland"
    FJ = "Fiji"
    FK = "Falkland Islands"
    FM = "Micronesia"
    FO = "Faroe Islands"
    FR = "France"
    GA = "Gabon"
    GB = "United Kingdom"
    GD = "Grenada"
    GE = "Georgia"
    GF = "French Guiana"
    GG = "Guernsey"
    GH = "Ghana"
    GI = "Gibraltar"
    GL = "Greenland"
    GM = "Gambia"
    GN = "Guinea"
    GP = "Guadeloupe"
    GQ = "Equatorial Guinea"
    GR = "Greece"
    GS = "South Georgia and the South Sandwich Islands"
    GT = "Guatemala"
    GU = "Guam"
    GW = "Guinea-Bissau"
    GY = "Guyana"
    HK = "Hong Kong"
    HM = "Heard Island and McDonald Islands"
    HN = "Honduras"
    HR = "Croatia"
    HT = "Haiti"
    HU = "Hungary"
    ID = "Indonesia"
    IE = "Ireland"
    IL = "Israel"
    IM = "Isle of Man"
    IN = "India"
    IO = "British Indian Ocean Territory"
    IQ = "Iraq"
    IR = "Iran"
    IS = "Iceland"
    IT = "Italy"
    JE = "Jersey"
    JM = "Jamaica"
    JO = "Jordan"
    JP = "Japan"
    KE = "Kenya"
    KG = "Kyrgyzstan"
    KH = "Cambodia"
    KI = "Kiribati"
    KM = "Comoros"
    KN = "Saint Kitts and Nevis"
    KP = "North Korea"
    KR = "South Korea"
    KW = "Kuwait"
    KY = "Cayman Islands"
    KZ = "Kazakhstan"
    LA = "Laos"
    LB = "Lebanon"
    LC = "Saint Lucia"
    LI = "Liechtenstein"
    LK = "Sri Lanka"
    LR = "Liberia"
    LS = "Lesotho"
    LT = "Lithuania"
    LU = "Luxembourg"
    LV = "Latvia"
    LY = "Libya"
    MA = "Morocco"
    MC = "Monaco"
    MD = "Moldova"
    ME = "Montenegro"
    MF = "Saint Martin"
    MG = "Madagascar"
    MH = "Marshall Islands"
    MK = "North Macedonia"
    ML = "Mali"
    MM = "Myanmar"
    MN = "Mongolia"
    MO = "Macao"
    MP = "Northern Mariana Islands"
    MQ = "Martinique"
    MR = "Mauritania"
    MS = "Montserrat"
    MT = "Malta"
    MU = "Mauritius"
    MV = "Maldives"
    MW = "Malawi"
    MX = "Mexico"
    MY = "Malaysia"
    MZ = "Mozambique"
    NA = "Namibia"
    NC = "New Caledonia"
    NE = "Niger"
    NF = "Norfolk Island"
    NG = "Nigeria"
    NI = "Nicaragua"
    NL = "Netherlands"
    NO = "Norway"
    NP = "Nepal"
    NR = "Nauru"
    NU = "Niue"
    NZ = "New Zealand"
    OM = "Oman"
    PA = "Panama"
    PE = "Peru"
    PF = "French Polynesia"
    PG = "Papua New Guinea"
    PH = "Philippines"
    PK = "Pakistan"
    PL = "Poland"
    PM = "Saint Pierre and Miquelon"
    PN = "Pitcairn"
    PR = "Puerto Rico"
    PS = "Palestine"
    PT = "Portugal"
    PW = "Palau"
    PY = "Paraguay"
    QA = "Qatar"
    RE = "Réunion"
    RO = "Romania"
    RS = "Serbia"
    RU = "Russia"
    RW = "Rwanda"
    SA = "Saudi Arabia"
    SB = "Solomon Islands"
    SC = "Seychelles"
    SD = "Sudan"
    SE = "Sweden"
    SG = "Singapore"
    SH = "Saint Helena"
    SI = "Slovenia"
    SJ = "Svalbard and Jan Mayen"
    SK = "Slovakia"
    SL = "Sierra Leone"
    SM = "San Marino"
    SN = "Senegal"
    SO = "Somalia"
    SR = "Suriname"
    SS = "South Sudan"
    ST = "Sao Tome and Principe"
    SV = "El Salvador"
    SX = "Sint Maarten"
    SY = "Syria"
    SZ = "Eswatini"
    TC = "Turks and Caicos Islands"
    TD = "Chad"
    TF = "French Southern Territories"
    TG = "Togo"
    TH = "Thailand"
    TJ = "Tajikistan"
    TK = "Tokelau"
    TL = "Timor-Leste"
    TM = "Turkmenistan"
    TN = "Tunisia"
    TO = "Tonga"
    TR = "Turkey"
    TT = "Trinidad and Tobago"
    TV = "Tuvalu"
    TW = "Taiwan"
    TZ = "Tanzania"
    UA = "Ukraine"
    UG = "Uganda"
    UM = "United States Minor Outlying Islands"
    US = "United States of America"
    UY = "Uruguay"
    UZ = "Uzbekistan"
    VA = "Holy See"
    VC = "Saint Vincent and the Grenadines"
    VE = "Venezuela"
    VG = "British Virgin Islands"
    VI = "U.S. Virgin Islands"
    VN = "Viet Nam"
    VU = "Vanuatu"
    WF = "Wallis and Futuna"
    WS = "Samoa"
    YE = "Yemen"
    YT = "Mayotte"
    ZA = "South Africa"
    ZM = "Zambia"
    ZW = "Zimbabwe"

