version: 0.1.0
contract: '1'
kubernetes:
    minimumMinor: 34
    maximumMinor: 35
upgradeFrom: []
components:
    knative: v1.23.0
    kourier: v1.23.0
    cnpg: v1.29.1
    rook: v1.19.11
    ceph: v19.2.6
stages:
    - boundaries
    - operators/serving-crds
    - operators/serving
    - operators/kourier
    - operators/cnpg
    - operators/rook-crds
    - operators/rook
    - infrastructure
