gateway:
    address: 127.0.0.1
    service:
        nodePort: 30443
        type: NodePort

gatewayAllowedSourceCidr: 172.30.0.0/24

storage:
    address: 127.0.0.1
    dnsNames:
        - storage.localhost
    service:
        nodePort: 30943
        type: NodePort

rustfs:
    storage:
        name: local-path
        dataStorageSize: 1Gi
