gateway:
    address: 127.0.0.1
    service:
        nodePort: 30443
        type: NodePort

gatewayAllowedSourceCidr: 127.0.0.1/32

storage:
    address: 127.0.0.1
    dnsNames:
        - storage.localhost
    service:
        nodePort: 30943
        type: NodePort

rustfs:
    mode: standalone
    storage:
        name: local-path
        dataStorageSize: 1Gi
        logStorageSize: 1Gi
