/** Enumerated XML values mirrored from sdk/longlink/.static/xsd/types.xsd. */
export const xmlTypeValues = {
    elevation: ['none', 'low', 'med', 'high'],
    fieldStatusVariant: ['attached', 'detached', 'tooltip'],
    layerPlacement: ['above', 'below', 'start', 'end'],
    selectorVariant: ['input', 'ghost'],
    actionMethod: ['DELETE', 'GET', 'PATCH', 'POST', 'PUT'],
    size: ['sm', 'md', 'lg'],
    avatarSize: ['xsm', 'sm', 'md', 'lg', 'xl'],
    iconSize: ['xsm', 'sm', 'md', 'lg'],
    iconColor: [
        'primary',
        'secondary',
        'tertiary',
        'disabled',
        'accent',
        'success',
        'error',
        'warning',
        'inherit',
        'blue',
        'red',
        'green',
        'gray',
        'cyan',
        'teal',
        'yellow',
        'orange',
        'pink',
        'purple',
    ],
    compactSize: ['sm', 'md'],
    orientation: ['horizontal', 'vertical'],
    spacing: [0, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 8, 10],
    inputStatus: ['warning', 'error', 'success'],
    buttonVariant: ['primary', 'secondary', 'ghost', 'destructive'],
    buttonHtml: ['button', 'submit', 'reset'],
    badgeVariant: [
        'neutral',
        'info',
        'success',
        'warning',
        'error',
        'blue',
        'cyan',
        'green',
        'orange',
        'pink',
        'purple',
        'red',
        'teal',
        'yellow',
    ],
    cardVariant: [
        'default',
        'transparent',
        'muted',
        'blue',
        'cyan',
        'gray',
        'green',
        'orange',
        'pink',
        'purple',
        'red',
        'teal',
        'yellow',
    ],
    dialogPurpose: ['required', 'form', 'info'],
    dialogVariant: ['standard', 'fullscreen'],
    dividerVariant: ['subtle', 'strong'],
    fileInputMode: ['dropzone', 'input'],
    formDirection: ['vertical', 'horizontal', 'horizontal-labels'],
    gridRepeat: ['fill', 'fit'],
    align: ['start', 'center', 'end'],
    boxAlign: ['start', 'center', 'end', 'stretch'],
    headingType: ['display-1', 'display-2', 'display-3'],
    truncateTooltip: [true, false, 'above', 'below', 'start', 'end'],
    wordBreak: ['break-word', 'break-all'],
    textWrap: ['wrap', 'nowrap', 'balance', 'pretty'],
    textColor: ['primary', 'secondary', 'disabled', 'placeholder', 'accent', 'inherit'],
    sliderValueDisplay: ['tooltip', 'text', 'none'],
    stackJustify: ['start', 'center', 'end', 'between', 'around', 'evenly'],
    stackWrap: ['nowrap', 'wrap', 'wrap-reverse'],
    switchLabelPosition: ['start', 'end'],
    switchLabelSpacing: ['hug', 'spread'],
    tableDensity: ['compact', 'balanced', 'spacious'],
    tableDividers: ['rows', 'columns', 'grid', 'none'],
    tableVerticalAlign: ['middle', 'top', 'bottom'],
    tableTextOverflow: ['wrap', 'truncate'],
    tabLayout: ['hug', 'fill'],
    typography: ['body', 'large', 'label', 'supporting', 'code', 'display-1', 'display-2', 'display-3', 'inherit'],
    fontWeight: ['normal', 'medium', 'semibold', 'bold'],
    textDisplay: ['inline', 'block'],
    textElement: ['span', 'p', 'div', 'label', 'h1', 'h2', 'h3'],
    textSize: ['4xs', '3xs', '2xs', 'xsm', 'sm', 'base', 'lg', 'xl', '2xl', '3xl', '4xl'],
    textInputKind: ['text', 'password', 'email'],
} as const;
