// Generated by longlink dev from the installed SDK. Do not edit this local copy.
// Editor declarations only. The shared frontend supplies these APIs at runtime.

type ViewNode = React.JSX.Element | string | number | boolean | null | undefined | ViewNode[];
type ViewComponent<P> = (props: P & { children?: ViewNode }) => React.JSX.Element;
type ViewProps = { params: Readonly<Record<string, string>> };
type Spacing = 0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10;

/** @category Action @group Button */
type ViewMouseEvent = Omit<MouseEvent, 'currentTarget'> & { currentTarget: HTMLElement; nativeEvent: MouseEvent };

/** @category Action @group Button */
type ButtonProps = {
    label: string;
    variant?: 'primary' | 'secondary' | 'ghost' | 'destructive';
    size?: 'sm' | 'md' | 'lg';
    type?: 'button' | 'submit' | 'reset';
    name?: string;
    value?: string | number | readonly string[];
    form?: string;
    icon?: string;
    endContent?: ViewNode;
    tooltip?: string;
    width?: number | string;
    isDisabled?: boolean;
    disabled?: boolean;
    href?: string;
    onClick?: (event: ViewMouseEvent) => void | Promise<void>;
};

/** @category Action @group DropdownMenu */
type DropdownMenuItemData = {
    id?: string;
    label: ViewNode;
    icon?: string;
    description?: ViewNode;
    endContent?: ViewNode;
    variant?: 'default' | 'destructive';
    isDisabled?: boolean;
    hasCloseOnSelect?: boolean;
    onClick?: () => void;
    items?: DropdownMenuOption[];
};

/** @category Action @group DropdownMenu */
type DropdownMenuOption =
    | DropdownMenuItemData
    | { type: 'divider' }
    | {
          type: 'section';
          id?: string;
          title?: string;
          items: DropdownMenuItemData[];
      };

/** @category Runtime */
declare namespace React {
    namespace JSX {
        interface Element {
            readonly type: unknown;
            readonly props: unknown;
        }

        interface ElementChildrenAttribute {
            children: unknown;
        }

        interface IntrinsicElements {
            [name: string]: Record<string, unknown>;
        }
    }
}

/** Groups JSX children without a DOM wrapper. @category Runtime @group Functions */
declare const Fragment: ViewComponent<{
    key?: string | number;
}>;

/**
 * Returns the current state and a setter. Pass a value or an initializer function; updates can use the previous state.
 * @category Runtime
 * @group Hooks
 */
declare function useState<T = undefined>(initial?: T | (() => T)): [T, (value: T | ((previous: T) => T)) => void];

/**
 * Synchronizes with external systems after rendering. Return a cleanup function to release timers or subscriptions. Include every reactive value used by the effect in its dependencies.
 * @category Runtime
 * @group Hooks
 */
declare function useEffect(effect: () => void | (() => void), dependencies?: readonly unknown[]): void;

/**
 * Caches a calculated value until its dependencies change. Use it for expensive calculations, not required application state.
 * @category Runtime
 * @group Hooks
 */
declare function useMemo<T>(factory: () => T, dependencies: readonly unknown[]): T;

/**
 * Returns a stable object with a mutable current property. Changing current does not trigger a render.
 * @category Runtime
 * @group Hooks
 */
declare function useRef<T>(initial: T): { current: T };

/**
 * Navigates within the current Solution using a scoped path.
 * @category Runtime
 * @group Functions
 */
declare function navigate(path: string): void;

/**
 * Requests a Solution operation and returns its data. Options support the HTTP method, JSON, form data, and binary responses. Successful writes automatically refresh cached View data.
 * @category Runtime
 * @group Functions
 */
declare function request<T = unknown>(
    path: string,
    options?: {
        method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
        json?: unknown;
        form?: [string, string | Blob][];
        binary?: boolean;
    },
): Promise<T>;

/**
 * Returns Solution data and an awaitable invalidator scoped to the full request path. The renderer handles initial loading, errors, and retry.
 * @category Runtime
 * @group Hooks
 */
declare function useApi<T = unknown>(path: string): readonly [T, () => Promise<void>];

/** @category Layouts */
declare function Stack(props: {
    children?: ViewNode;
    /** Spacing between items. */
    gap?: Spacing;
    padding?: Spacing;
    direction?: 'horizontal' | 'vertical';
    justify?: 'start' | 'center' | 'end' | 'between' | 'around' | 'evenly';
    align?: 'start' | 'center' | 'end' | 'stretch';
    wrap?: 'nowrap' | 'wrap' | 'wrap-reverse';
}): React.JSX.Element;

/** @category Display */
declare function Heading(props: { children?: ViewNode; level?: 1 | 2 | 3 | 4 | 5 | 6 }): React.JSX.Element;

/** @category Display */
declare function Text(props: {
    children?: ViewNode;
    color?: 'primary' | 'secondary';
    type?: 'body' | 'large' | 'label' | 'supporting' | 'code';
}): React.JSX.Element;

/** @category Action */
declare function Button(props: ButtonProps): React.JSX.Element;

/** @category Action */
declare function ButtonGroup(props: {
    children?: ViewNode;
    label: string;
    orientation?: 'horizontal' | 'vertical';
    size?: 'sm' | 'md' | 'lg';
    isDisabled?: boolean;
}): React.JSX.Element;

/** @category Action */
declare function DropdownMenu(props: {
    button?: {
        label: string;
        variant?: 'primary' | 'secondary' | 'ghost' | 'destructive';
        size?: 'sm' | 'md' | 'lg';
        isDisabled?: boolean;
    };
    items: DropdownMenuOption[];
    isMenuOpen?: boolean;
    onOpenChange?: (isOpen: boolean) => void;
}): React.JSX.Element;

/** @category Action */
declare function IconButton(props: {
    label: string;
    icon: string;
    variant?: 'primary' | 'secondary' | 'ghost' | 'destructive';
    size?: 'sm' | 'md' | 'lg';
    tooltip?: string;
    isDisabled?: boolean;
    onClick?: (event: ViewMouseEvent) => void | Promise<void>;
}): React.JSX.Element;

/** @category Action */
declare function Link(props: { to: string; children?: ViewNode }): React.JSX.Element;

/** @category Display */
declare function Badge(props: {
    label?: ViewNode;
    icon?: string;
    variant?:
        | 'neutral'
        | 'info'
        | 'success'
        | 'warning'
        | 'error'
        | 'blue'
        | 'cyan'
        | 'green'
        | 'orange'
        | 'pink'
        | 'purple'
        | 'red'
        | 'teal'
        | 'yellow';
}): React.JSX.Element;

/** @category Display */
declare function StatusDot(props: {
    label: string;
    variant: 'success' | 'warning' | 'error' | 'accent' | 'neutral';
    tooltip?: string;
}): React.JSX.Element;

/** @category Display */
declare function Avatar(props: {
    name?: string;
    shape?: 'circle' | 'rounded';
    src?: string | null;
    alt?: string;
    size?: 'sm' | 'md' | 'lg';
}): React.JSX.Element;

/** @category Layouts */
declare function Dialog(props: {
    children?: ViewNode;
    'aria-label': string;
    isOpen: boolean;
    onOpenChange: (open: boolean) => void;
    purpose?: 'form' | 'info' | 'required';
}): React.JSX.Element;

/** Shared props for form controls. */
type FieldProps = {
    label: string;
    description?: string;
    /** Includes the themed control's value under this form submission name. */
    name?: string;
    /** Requires a value before native form submission. */
    required?: boolean;
    /** Prevents interaction and excludes the field from submission. */
    disabled?: boolean;
    /** Retains submitted values while preventing editing where supported. */
    readOnly?: boolean;
    isRequired?: boolean;
    isDisabled?: boolean;
    width?: number | string;
};

/** Submits named themed fields and ordinary HTML inputs to a Solution API endpoint. @category Form */
declare function Form(props: {
    /** Named controls, ordinary HTML fields, and layout components. */
    children?: ViewNode;
    /** Solution-relative API path; external URLs are not supported. */
    action: string;
    /** Only POST is supported; defaults to post. Use request() for other methods. */
    method?: 'post';
    /** Native form ID for associating external submit or reset buttons. */
    id?: string;
    /** Runs after a successful write and automatic cached-data refresh. */
    onSuccess?: (data: unknown) => void | Promise<void>;
}): React.JSX.Element;

/** @category Form @group DateInput */
type ISODateString = `${number}${number}${number}${number}-${number}${number}-${number}${number}`;

/** @category Form @group DateInput */
type DateInputProps = FieldProps & {
    value?: ISODateString;
    defaultValue?: ISODateString;
    onChange?: (value: ISODateString | undefined) => void;
    min?: ISODateString;
    max?: ISODateString;
    /** Additional constraints applied to the themed calendar picker. */
    dateConstraints?: readonly ((date: Date) => boolean)[];
    placeholder?: string;
    hasClear?: boolean;
    size?: 'sm' | 'md' | 'lg';
};

/** @category Form */
declare function DateInput(props: DateInputProps): React.JSX.Element;

/** @category Form @group TimeInput */
type ISOTimeString = string & { readonly __brand: 'ISOTimeString' };

/** @category Form */
declare function TimeInput(
    props: FieldProps & {
        value?: ISOTimeString;
        defaultValue?: ISOTimeString;
        onChange?: (value: ISOTimeString | undefined) => void;
        min?: ISOTimeString;
        max?: ISOTimeString;
        hasSeconds?: boolean;
        hasClear?: boolean;
        hourFormat?: '12h' | '24h';
        increment?: number;
        placeholder?: string;
        size?: 'sm' | 'md' | 'lg';
    },
): React.JSX.Element;

/** @category Form */
declare function TextInput(
    props: FieldProps & {
        value?: string;
        defaultValue?: string;
        onChange?: (value: string) => void;
        placeholder?: string;
        type?: 'text' | 'password' | 'email';
        size?: 'sm' | 'md' | 'lg';
        htmlName?: string;
        autoComplete?: string;
        isReadOnly?: boolean;
        hasClear?: boolean;
        hasAutoFocus?: boolean;
        startIcon?: ViewNode;
        onEnter?: () => void;
    },
): React.JSX.Element;

/** @category Form */
declare function TextArea(
    props: FieldProps & {
        value?: string;
        defaultValue?: string;
        onChange?: (value: string) => void;
        placeholder?: string;
        rows?: number;
        maxLength?: number;
        isReadOnly?: boolean;
        hasAutoFocus?: boolean;
        htmlName?: string;
        autoComplete?: string;
    },
): React.JSX.Element;

/** @category Form */
declare function NumberInput(
    props: FieldProps & {
        value?: number | null;
        defaultValue?: number;
        min?: number | null;
        max?: number | null;
        step?: number | null;
        placeholder?: string;
        size?: 'sm' | 'md' | 'lg';
        isReadOnly?: boolean;
        units?: string | null;
        isIntegerOnly?: boolean;
        htmlName?: string;
        autoComplete?: string;
    } & (
            | { hasClear?: false; onChange?: (value: number) => void }
            | { hasClear: true; onChange?: (value: number | null) => void }
        ),
): React.JSX.Element;

/** @category Form @group Selector */
type SelectorOptionData = {
    value: string;
    label?: string;
    description?: ViewNode;
    icon?: string;
    disabled?: boolean;
};

/** @category Form @group Selector */
type SelectorOptionType =
    | string
    | SelectorOptionData
    | { type: 'divider' }
    | {
          type: 'section';
          title?: string;
          options: SelectorOptionData[];
      };

/** @category Form */
declare function MultiSelector(
    props: FieldProps & {
        options: SelectorOptionType[];
        value?: string[];
        defaultValue?: string[];
        onChange?: (value: string[]) => void;
        placeholder?: string;
        size?: 'sm' | 'md' | 'lg';
        hasSelectAll?: boolean;
        hasSearch?: boolean;
        isReadOnly?: boolean;
        htmlName?: string;
        hasClear?: boolean;
    },
): React.JSX.Element;

/** @category Form */
declare function Selector(
    props: FieldProps & {
        options: SelectorOptionType[];
        defaultValue?: string;
        hasSearch?: boolean;
        placeholder?: string;
        size?: 'sm' | 'md' | 'lg';
        isReadOnly?: boolean;
        htmlName?: string;
    } & (
            | { hasClear?: false; value?: string; onChange?: (value: string) => void }
            | { hasClear: true; value?: string | null; onChange?: (value: string | null) => void }
        ),
): React.JSX.Element;

/** @category Form */
declare function FileInput(
    props: FieldProps & {
        value?: File | File[] | null;
        onChange?: (value: File | File[] | null) => void;
        accept?: string;
        isMultiple?: boolean;
        multiple?: boolean;
        maxSize?: number;
        maxFiles?: number;
        placeholder?: string;
        mode?: 'input' | 'dropzone';
    },
): React.JSX.Element;

/** @category Display */
declare function FileViewer(props: {
    /** Scoped Solution operation path returning the file to preview. */
    src: string;
    /** Accessible label for the preview trigger and file dialog. */
    title: string;
}): React.JSX.Element;

/** @category Layouts */
declare function Grid(props: { children?: ViewNode; columns?: number; gap?: Spacing }): React.JSX.Element;

/** @category Layouts @group Grid */
declare function GridSpan(props: {
    /** Content rendered inside the grid item. */
    children?: ViewNode;
    /** Number of columns to occupy, or full to span the entire grid. */
    columns?: number | 'full';
}): React.JSX.Element;

/** @category Layouts @group Stack */
declare function StackItem(props: {
    /** Content rendered inside the stack item. */
    children?: ViewNode;
    size?: 'static' | 'fill';
    isScrollable?: boolean;
    /** Overrides this item's cross-axis alignment; omitted values inherit the parent alignment. */
    crossAlignSelf?: 'start' | 'center' | 'end' | 'stretch';
}): React.JSX.Element;

/** @category Layouts @group Card */
type CardProps = {
    /** Content rendered inside the card. */
    children?: ViewNode;
    padding?: 0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10;
    variant?:
        | 'default'
        | 'transparent'
        | 'muted'
        | 'blue'
        | 'cyan'
        | 'gray'
        | 'green'
        | 'orange'
        | 'pink'
        | 'purple'
        | 'red'
        | 'teal'
        | 'yellow';
    /** Card width; numbers are pixels and strings are CSS sizes. */
    width?: number | string;
    /** Card height; numbers are pixels and strings are CSS sizes. */
    height?: number | string;
    /** Maximum card width. */
    maxWidth?: number | string;
    /** Minimum card height. */
    minHeight?: number | string;
    /** Makes the card and its descendants non-interactive. */
    inert?: boolean;
    /** Hides the card from assistive technologies. */
    'aria-hidden'?: boolean | 'true' | 'false';
    label?: string;
    /** Makes the card clickable and receives its activation event. */
    onClick?: (event: ViewMouseEvent) => void;
    /** Makes the card a navigation target when no selection callback is supplied. */
    href?: string;
    target?: string;
    isDisabled?: boolean;
    isSelected?: boolean;
    /** Makes the card selectable and receives its next selection state; takes priority over activation. */
    onChange?: (isSelected: boolean) => void;
};

/** @category Layouts */
declare function Card(props: CardProps): React.JSX.Element;

/** @category Layouts */
declare function Collapsible(props: {
    children?: ViewNode;
    trigger: ViewNode;
    defaultIsOpen?: boolean;
    isOpen?: boolean;
    isDisabled?: boolean;
    onOpenChange?: (isOpen: boolean) => void;
}): React.JSX.Element;

/** @category Form */
declare function CheckboxInput(
    props: FieldProps & {
        value?: boolean | 'indeterminate';
        checked?: boolean;
        defaultChecked?: boolean;
        onChange?: (value: boolean) => void;
        isReadOnly?: boolean;
        htmlName?: string;
        size?: 'sm' | 'md';
    },
): React.JSX.Element;

/** @category Form */
declare function Switch(
    props: FieldProps & {
        value?: boolean;
        checked?: boolean;
        defaultChecked?: boolean;
        onChange?: (value: boolean) => void;
        htmlName?: string;
        size?: 'sm' | 'md';
    },
): React.JSX.Element;

/** @category Form */
declare function Slider(
    props: FieldProps & {
        min?: number;
        max?: number;
        step?: number;
        htmlName?: string;
    } & (
            | {
                  value?: number;
                  defaultValue?: number;
                  onChange?: (value: number) => void;
                  onChangeEnd?: (value: number) => void;
              }
            | {
                  value?: [number, number];
                  defaultValue?: [number, number];
                  onChange?: (value: [number, number]) => void;
                  onChangeEnd?: (value: [number, number]) => void;
                  minStepsBetweenThumbs?: number;
              }
        ),
): React.JSX.Element;

/** @category Form */
declare function RadioList(
    props: FieldProps & {
        children?: ViewNode;
        value?: string;
        defaultValue?: string;
        onChange?: (value: string) => void;
        orientation?: 'vertical' | 'horizontal';
        htmlName?: string;
        size?: 'sm' | 'md';
    },
): React.JSX.Element;

/** @category Form @group RadioList */
declare function RadioListItem(props: {
    /** Visible label identifying this choice. */
    label: string;
    /** Value passed to the surrounding RadioList when selected. */
    value: string;
    /** Optional helper text explaining the choice. */
    description?: string;
    isDisabled?: boolean;
}): React.JSX.Element;

/** @category Action */
declare function MoreMenu(props: {
    items: DropdownMenuOption[];
    label?: string;
    icon?: string;
    isDisabled?: boolean;
    onOpenChange?: (isOpen: boolean) => void;
}): React.JSX.Element;

/** @category Layouts */
declare function Menu(props: {
    /** MenuSection elements defining navigation and content. */
    children?: ViewNode;
    gap?: 0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10;
}): React.JSX.Element;

/** @category Layouts @group Menu */
declare function MenuSection(props: {
    /** MenuItem elements or nested MenuSubSection groups. */
    children?: ViewNode;
    /** Hides the section heading; visible by default. */
    isHeaderHidden?: boolean;
    /** Section heading displayed in the navigation. */
    title: string;
}): React.JSX.Element;

/** @category Layouts @group Menu */
declare function MenuItem(props: {
    /** Content mounted beside the navigation while this item is selected. */
    children?: ViewNode;
    /** Optional LongLink icon name displayed beside the label. */
    icon?: string;
    /** Navigation label; its lowercase, hyphenated form identifies the item's URL fragment. */
    label: string;
}): React.JSX.Element;

/** @category Layouts @group Menu */
declare function MenuSubSection(props: {
    /** MenuItem elements nested inside this collapsible group. */
    children?: ViewNode;
    /** Optional LongLink icon name displayed beside the group label. */
    icon?: string;
    /** Label displayed on the collapsible navigation group. */
    label: string;
}): React.JSX.Element;

/** @category Display */
declare function Icon(props: { icon: string; size: 'sm' | 'md' | 'lg' }): React.JSX.Element;

/** @category Display */
declare function CodeBlock(props: {
    code: string;
    language?: string;
    title?: string;
    isWrapped?: boolean;
}): React.JSX.Element;

/** @category Display */
declare function ProgressBar(props: {
    label: string;
    value?: number;
    max?: number;
    hasValueLabel?: boolean;
    variant?: 'accent' | 'success' | 'warning' | 'error' | 'neutral';
}): React.JSX.Element;

/** @category Layouts */
declare function Stepper(props: {
    children?: ViewNode;
    activeStep?: number;
    orientation?: 'horizontal' | 'vertical';
}): React.JSX.Element;

/** @category Layouts @group Stepper */
declare function Step(props: {
    /** Zero-based index of this step in the process. */
    step: number;
    /** Visible label identifying the step. */
    label: string;
}): React.JSX.Element;

/** @category Layouts */
declare function Tabs(props: {
    /** Tab elements defining labels and panel content. */
    children?: ViewNode;
    gap?: 0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10;
    hasDivider?: boolean;
    /** Receives the selected Tab value; use with value to control selection. */
    onChange?: (value: string) => void;
    /** Selected Tab value; omit for internal selection, initially choosing the first tab. */
    value?: string;
}): React.JSX.Element;

/** @category Layouts @group Tabs */
declare function Tab(props: {
    /** Panel content mounted only while this tab is selected. */
    children?: ViewNode;
    /** Unique value identifying this tab. */
    value: string;
    /** Visible tab label and accessible panel name. */
    label: string;
    /** Whether the tab is disabled. */
    isDisabled?: boolean;
}): React.JSX.Element;

/** @category Display */
declare function EmptyState(props: { title: string; isCompact?: boolean }): React.JSX.Element;

/** @category Display */
declare function Currency(props: {
    /** Amount to format in currency units. */
    value: number;
    /** ISO 4217 currency code, such as USD or CHF. */
    currency: string;
    /** Locale for formatting; omitted values use the viewer's locale. */
    locale?: string;
}): React.JSX.Element;

/** @category Display */
declare function Timestamp(props: {
    value: number | string;
    format?:
        | 'date'
        | 'date_long'
        | 'date_weekday'
        | 'date_time'
        | 'time'
        | 'relative'
        | 'system_date'
        | 'system_date_time'
        | 'system_time';
}): React.JSX.Element;

/** @category Display */
declare function Divider(props: {
    label?: ViewNode;
    variant?: 'subtle' | 'strong';
    orientation?: 'horizontal' | 'vertical';
    isFullBleed?: boolean;
}): React.JSX.Element;

/** @category Display */
declare function MetadataList(props: {
    children?: ViewNode;
    columns?: 'multi' | 'single' | number;
    title?: ViewNode;
}): React.JSX.Element;

/** @category Display @group MetadataList */
declare function MetadataListItem(props: {
    /** Value rendered beside the metadata label. */
    children?: ViewNode;
    /** Label identifying the metadata value. */
    label: string;
    /** Optional icon displayed beside the metadata label. */
    icon?: string;
}): React.JSX.Element;

/** @category Display @group Table */
type ColumnWidth = { type: 'proportional'; value: number; minWidth?: number } | { type: 'pixel'; value: number };

/** @category Display @group Table */
declare function proportional(
    value?: number,
    options?: { minWidth?: number },
): Extract<ColumnWidth, { type: 'proportional' }>;

/** @category Display @group Table */
declare function pixel(value: number): Extract<ColumnWidth, { type: 'pixel' }>;

/** @category Display */
declare function Table<T extends Record<string, unknown>>(props: {
    data: T[];
    idKey?: (keyof T & string) | ((row: T) => string | number);
    density?: 'compact' | 'balanced' | 'spacious';
    hasHover?: boolean;
    isStriped?: boolean;
    columns?: {
        key: string;
        header?: ViewNode;
        width?: ColumnWidth;
        align?: 'start' | 'center' | 'end';
        renderCell?: (row: T) => ViewNode;
    }[];
}): React.JSX.Element;
