// Generated by longlink dev from the installed SDK. Do not edit this local copy.
// Editor declarations only. The shared frontend supplies these APIs at runtime.

type ViewNode = React.JSX.Element | string | number | boolean | null | undefined | ViewNode[];
type ViewComponent<P> = (props: P & { children?: ViewNode }) => React.JSX.Element;
type ViewProps = { params: Readonly<Record<string, string>> };
type Spacing = 0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10;

/** @category Action @group Button */
type ViewMouseEvent = Omit<MouseEvent, 'currentTarget'> & { currentTarget: HTMLElement; nativeEvent: MouseEvent };

/** @category Action @group Button */
type ButtonProps = {
    label: string;
    variant?: 'primary' | 'secondary' | 'ghost' | 'destructive';
    size?: 'sm' | 'md' | 'lg';
    type?: 'button' | 'submit' | 'reset';
    name?: string;
    value?: string | number | readonly string[];
    form?: string;
    icon?: ViewNode;
    endContent?: ViewNode;
    tooltip?: string;
    width?: number | string;
    isDisabled?: boolean;
    href?: string;
    onClick?: (event: ViewMouseEvent) => void | Promise<void>;
};

/** @category Action @group DropdownMenu */
type DropdownMenuItemData = {
    id?: string;
    label: ViewNode;
    icon?: ViewNode;
    description?: ViewNode;
    endContent?: ViewNode;
    variant?: 'default' | 'destructive';
    isDisabled?: boolean;
    hasCloseOnSelect?: boolean;
    onClick?: () => void;
    items?: DropdownMenuOption[];
};

/** @category Action @group DropdownMenu */
type DropdownMenuOption =
    | DropdownMenuItemData
    | { type: 'divider' }
    | {
          type: 'section';
          id?: string;
          title?: string;
          items: DropdownMenuItemData[];
      };

/** @category Runtime */
declare namespace React {
    namespace JSX {
        interface Element {
            readonly type: unknown;
            readonly props: unknown;
        }

        interface ElementChildrenAttribute {
            children: unknown;
        }

        interface IntrinsicElements {
            [name: string]: Record<string, unknown>;
        }
    }
}

/** Groups JSX children without a DOM wrapper. @category Runtime @group Functions */
declare const Fragment: ViewComponent<{
    key?: string | number;
}>;

/**
 * Returns the current state and a setter. Pass a value or an initializer function; updates can use the previous state.
 * @category Runtime
 * @group Hooks
 */
declare function useState<T = undefined>(initial?: T | (() => T)): [T, (value: T | ((previous: T) => T)) => void];

/**
 * Synchronizes with external systems after rendering. Return a cleanup function to release timers or subscriptions. Include every reactive value used by the effect in its dependencies.
 * @category Runtime
 * @group Hooks
 */
declare function useEffect(effect: () => void | (() => void), dependencies?: readonly unknown[]): void;

/**
 * Caches a calculated value until its dependencies change. Use it for expensive calculations, not required application state.
 * @category Runtime
 * @group Hooks
 */
declare function useMemo<T>(factory: () => T, dependencies: readonly unknown[]): T;

/**
 * Returns a stable object with a mutable current property. Changing current does not trigger a render.
 * @category Runtime
 * @group Hooks
 */
declare function useRef<T>(initial: T): { current: T };

/**
 * Navigates within the current Solution using a scoped path.
 * @category Runtime
 * @group Functions
 */
declare function navigate(path: string): void;

/**
 * Requests a Solution operation and returns its data. Options support the HTTP method, JSON, form data, and binary responses. Successful writes automatically refresh cached View data.
 * @category Runtime
 * @group Functions
 */
declare function request<T = unknown>(
    path: string,
    options?: {
        method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
        json?: unknown;
        form?: [string, string | Blob][];
        binary?: boolean;
    },
): Promise<T>;

/**
 * Returns Solution data and an awaitable invalidator scoped to the full request path. The renderer handles initial loading, errors, and retry.
 * @category Runtime
 * @group Hooks
 */
declare function useApi<T = unknown>(path: string): readonly [T, () => Promise<void>];

/** @category Layouts */
declare function Stack(props: {
    children?: ViewNode;
    gap?: Spacing;
    padding?: Spacing;
    direction?: 'horizontal' | 'vertical';
    justify?: 'start' | 'center' | 'end' | 'between' | 'around' | 'evenly';
    align?: 'start' | 'center' | 'end' | 'stretch';
    wrap?: 'nowrap' | 'wrap' | 'wrap-reverse';
}): React.JSX.Element;

/** @category Display */
declare function Heading(props: { children?: ViewNode; level?: 1 | 2 | 3 | 4 | 5 | 6 }): React.JSX.Element;

/** @category Display */
declare function Text(props: {
    children?: ViewNode;
    color?: 'primary' | 'secondary';
    type?: 'body' | 'large' | 'label' | 'supporting' | 'code';
}): React.JSX.Element;

/** @category Action */
declare function Button(props: ButtonProps): React.JSX.Element;

/** @category Action */
declare function ButtonGroup(props: {
    children?: ViewNode;
    label: string;
    orientation?: 'horizontal' | 'vertical';
    size?: 'sm' | 'md' | 'lg';
    isDisabled?: boolean;
}): React.JSX.Element;

/** @category Action */
declare function DropdownMenu(props: {
    button?: {
        label: string;
        variant?: 'primary' | 'secondary' | 'ghost' | 'destructive';
        size?: 'sm' | 'md' | 'lg';
        isDisabled?: boolean;
    };
    items: DropdownMenuOption[];
    isMenuOpen?: boolean;
    onOpenChange?: (isOpen: boolean) => void;
}): React.JSX.Element;

/** @category Action */
declare function IconButton(props: {
    label: string;
    icon: ViewNode;
    variant?: 'primary' | 'secondary' | 'ghost' | 'destructive';
    size?: 'sm' | 'md' | 'lg';
    tooltip?: string;
    isDisabled?: boolean;
    onClick?: (event: ViewMouseEvent) => void | Promise<void>;
}): React.JSX.Element;

/** @category Action */
declare function Link(props: { to: string; children?: ViewNode }): React.JSX.Element;

/** @category Display */
declare function Badge(props: {
    label?: ViewNode;
    icon?: ViewNode;
    variant?:
        | 'neutral'
        | 'info'
        | 'success'
        | 'warning'
        | 'error'
        | 'blue'
        | 'cyan'
        | 'green'
        | 'orange'
        | 'pink'
        | 'purple'
        | 'red'
        | 'teal'
        | 'yellow';
}): React.JSX.Element;

/** @category Display */
declare function StatusDot(props: {
    label: string;
    variant: 'success' | 'warning' | 'error' | 'accent' | 'neutral';
    tooltip?: string;
}): React.JSX.Element;

/** @category Display */
declare function Avatar(props: {
    name?: string;
    shape?: 'circle' | 'rounded';
    src?: string | null;
    alt?: string;
    size?: 'sm' | 'md' | 'lg';
}): React.JSX.Element;

/** @category Layouts */
declare function Dialog(props: {
    children?: ViewNode;
    'aria-label': string;
    isOpen: boolean;
    onOpenChange: (open: boolean) => void;
    purpose?: 'form' | 'info' | 'required';
}): React.JSX.Element;

/** Shared props for form controls. */
type FieldProps = {
    label: string;
    description?: string;
    isLabelHidden?: boolean;
    isRequired?: boolean;
    isDisabled?: boolean;
    status?: { type: 'warning' | 'error' | 'success'; message?: string };
    width?: number | string;
};

/** @category Form @group DateInput */
type ISODateString = `${number}${number}${number}${number}-${number}${number}-${number}${number}`;

/** @category Form @group DateInput */
type DateInputProps = FieldProps & {
    value?: ISODateString;
    onChange?: (value: ISODateString | undefined) => void;
    min?: ISODateString;
    max?: ISODateString;
    dateConstraints?: readonly ((date: Date) => boolean)[];
    placeholder?: string;
    hasClear?: boolean;
    size?: 'sm' | 'md' | 'lg';
};

/** @category Form */
declare function DateInput(props: DateInputProps): React.JSX.Element;

/** @category Form @group DateRangeInput */
type DateRange = { start: ISODateString; end: ISODateString };

/** @category Form */
declare function DateRangeInput(
    props: FieldProps & {
        value: DateRange | null;
        onChange: (value: DateRange | null) => void;
        min?: ISODateString;
        max?: ISODateString;
        dateConstraints?: readonly ((date: Date) => boolean)[];
        minRangeSpan?: number;
        maxRangeSpan?: number;
        placeholder?: string;
        size?: 'sm' | 'md' | 'lg';
        hasClear?: boolean;
    },
): React.JSX.Element;

/** @category Form @group DateTimeInput */
type ISODateTimeString = string & { readonly __brand: 'ISODateTimeString' };

/** @category Form */
declare function DateTimeInput(
    props: FieldProps & {
        value?: ISODateTimeString;
        onChange: (value: ISODateTimeString | undefined) => void;
        min?: ISODateTimeString;
        max?: ISODateTimeString;
        placeholder?: string;
        hasClear?: boolean;
        hasSeconds?: boolean;
        hourFormat?: '12h' | '24h';
        size?: 'sm' | 'md' | 'lg';
    },
): React.JSX.Element;

/** @category Form @group TimeInput */
type ISOTimeString = string & { readonly __brand: 'ISOTimeString' };

/** @category Form */
declare function TimeInput(
    props: FieldProps & {
        value?: ISOTimeString;
        onChange?: (value: ISOTimeString | undefined) => void;
        min?: ISOTimeString;
        max?: ISOTimeString;
        hasSeconds?: boolean;
        hasClear?: boolean;
        hourFormat?: '12h' | '24h';
        increment?: number;
        placeholder?: string;
        size?: 'sm' | 'md' | 'lg';
    },
): React.JSX.Element;

/** @category Form */
declare function TextInput(
    props: FieldProps & {
        value: string;
        onChange?: (value: string) => void;
        placeholder?: string;
        type?: 'text' | 'password' | 'email';
        size?: 'sm' | 'md' | 'lg';
        htmlName?: string;
        autoComplete?: string;
        isReadOnly?: boolean;
        hasClear?: boolean;
        hasAutoFocus?: boolean;
        startIcon?: ViewNode;
        onEnter?: () => void;
    },
): React.JSX.Element;

/** @category Form */
declare function TextArea(
    props: FieldProps & {
        value: string;
        onChange?: (value: string) => void;
        placeholder?: string;
        rows?: number;
        maxLength?: number;
        isReadOnly?: boolean;
        hasSpellCheck?: boolean;
        hasAutoFocus?: boolean;
        htmlName?: string;
        autoComplete?: string;
    },
): React.JSX.Element;

/** @category Form */
declare function NumberInput(
    props: FieldProps & {
        value: number | null | undefined;
        min?: number | null;
        max?: number | null;
        step?: number | null;
        placeholder?: string;
        size?: 'sm' | 'md' | 'lg';
        isReadOnly?: boolean;
        units?: string | null;
        isIntegerOnly?: boolean;
        htmlName?: string;
        autoComplete?: string;
    } & (
            | { hasClear?: false; onChange: (value: number) => void }
            | { hasClear: true; onChange: (value: number | null) => void }
        ),
): React.JSX.Element;

/** @category Form @group Selector */
type SelectorOptionData = {
    value: string;
    label?: string;
    description?: ViewNode;
    icon?: ViewNode;
    disabled?: boolean;
};

/** @category Form @group Selector */
type SelectorOptionType =
    | string
    | SelectorOptionData
    | { type: 'divider' }
    | {
          type: 'section';
          title?: string;
          options: SelectorOptionData[];
      };

/** @category Form */
declare function MultiSelector(
    props: FieldProps & {
        options: SelectorOptionType[];
        value: string[];
        onChange: (value: string[]) => void;
        placeholder?: string;
        size?: 'sm' | 'md' | 'lg';
        hasSelectAll?: boolean;
        hasSearch?: boolean;
        isReadOnly?: boolean;
        htmlName?: string;
        hasClear?: boolean;
    },
): React.JSX.Element;

/** @category Form */
declare function Selector(
    props: FieldProps & {
        options: SelectorOptionType[];
        hasSearch?: boolean;
        placeholder?: string;
        size?: 'sm' | 'md' | 'lg';
        isReadOnly?: boolean;
        htmlName?: string;
    } & (
            | { hasClear?: false; value?: string; onChange?: (value: string) => void }
            | { hasClear: true; value: string | null; onChange?: (value: string | null) => void }
        ),
): React.JSX.Element;

/** @category Form */
declare function FileInput(
    props: FieldProps & {
        value: File | File[] | null;
        onChange: (value: File | File[] | null) => void;
        accept?: string;
        isMultiple?: boolean;
        maxSize?: number;
        maxFiles?: number;
        placeholder?: string;
        mode?: 'input' | 'dropzone';
    },
): React.JSX.Element;

/** @category Display */
declare function FileViewer(props: { src: string; title: string }): React.JSX.Element;

/** @category Layouts */
declare function Grid(props: { children?: ViewNode; columns?: number; gap?: Spacing }): React.JSX.Element;

/** @category Layouts @group Grid */
declare function GridSpan(props: { children?: ViewNode; columns?: number | 'full' }): React.JSX.Element;

/** @category Layouts @group Stack */
declare function StackItem(props: {
    children?: ViewNode;
    size?: 'static' | 'fill';
    isScrollable?: boolean;
    crossAlignSelf?: 'start' | 'center' | 'end' | 'stretch';
}): React.JSX.Element;

/** @category Layouts @group Card */
type CardProps = {
    padding?: Spacing;
    variant?:
        | 'default'
        | 'transparent'
        | 'muted'
        | 'blue'
        | 'cyan'
        | 'gray'
        | 'green'
        | 'orange'
        | 'pink'
        | 'purple'
        | 'red'
        | 'teal'
        | 'yellow';
    width?: number | string;
    height?: number | string;
    maxWidth?: number | string;
    minHeight?: number | string;
    label?: string;
    onClick?: (event: ViewMouseEvent) => void;
    href?: string;
    target?: string;
    isDisabled?: boolean;
    isSelected?: boolean;
    onChange?: (isSelected: boolean) => void;
};

/** @category Layouts */
declare const Card: ViewComponent<CardProps>;

/** @category Layouts */
declare function Collapsible(props: {
    children?: ViewNode;
    trigger: ViewNode;
    defaultIsOpen?: boolean;
    isOpen?: boolean;
    isDisabled?: boolean;
    onOpenChange?: (isOpen: boolean) => void;
}): React.JSX.Element;

/** @category Form */
declare function CheckboxInput(
    props: FieldProps & {
        value: boolean | 'indeterminate';
        onChange?: (value: boolean) => void;
        isReadOnly?: boolean;
        htmlName?: string;
        size?: 'sm' | 'md';
    },
): React.JSX.Element;

/** @category Form */
declare function Switch(
    props: FieldProps & { value: boolean; onChange?: (value: boolean) => void; htmlName?: string; size?: 'sm' | 'md' },
): React.JSX.Element;

/** @category Form */
declare function Slider(
    props: FieldProps & {
        min?: number;
        max?: number;
        step?: number;
        htmlName?: string;
    } & (
            | { value: number; onChange?: (value: number) => void; onChangeEnd?: (value: number) => void }
            | {
                  value: [number, number];
                  onChange?: (value: [number, number]) => void;
                  onChangeEnd?: (value: [number, number]) => void;
                  minStepsBetweenThumbs?: number;
              }
        ),
): React.JSX.Element;

/** @category Form */
declare function RadioList(
    props: FieldProps & {
        children?: ViewNode;
        value: string;
        onChange: (value: string) => void;
        orientation?: 'vertical' | 'horizontal';
        htmlName?: string;
        size?: 'sm' | 'md';
    },
): React.JSX.Element;

/** @category Form @group RadioList */
declare function RadioListItem(props: {
    label: string;
    value: string;
    description?: string;
    isDisabled?: boolean;
}): React.JSX.Element;

/** @category Action */
declare function MoreMenu(props: {
    items: DropdownMenuOption[];
    label?: string;
    icon?: ViewNode;
    isDisabled?: boolean;
    onOpenChange?: (isOpen: boolean) => void;
}): React.JSX.Element;

/** @category Layouts */
declare function Menu(props: {
    children?: ViewNode;
    gap?: 0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10;
}): React.JSX.Element;

/** @category Layouts @group Menu */
declare function MenuSection(props: {
    children?: ViewNode;
    isHeaderHidden?: boolean;
    title: string;
}): React.JSX.Element;

/** @category Layouts @group Menu */
declare function MenuItem(props: { children?: ViewNode; id?: string; icon?: string; label: string }): React.JSX.Element;

/** @category Layouts @group Menu */
declare function MenuSubSection(props: { children?: ViewNode; icon?: string; label: string }): React.JSX.Element;

/** @category Display */
declare const Icon: ViewComponent<{
    icon: string;
    size: 'sm' | 'md' | 'lg';
}>;

/** @category Display */
declare function CodeBlock(props: {
    code: string;
    language?: string;
    title?: string;
    isWrapped?: boolean;
}): React.JSX.Element;

/** @category Display */
declare function ProgressBar(props: {
    label: string;
    value?: number;
    max?: number;
    isLabelHidden?: boolean;
    hasValueLabel?: boolean;
    variant?: 'accent' | 'success' | 'warning' | 'error' | 'neutral';
    isIndeterminate?: boolean;
}): React.JSX.Element;

/** @category Layouts */
declare function Stepper(props: {
    children?: ViewNode;
    activeStep?: number;
    orientation?: 'horizontal' | 'vertical';
}): React.JSX.Element;

/** @category Layouts @group Stepper */
declare function Step(props: { step: number; label: string }): React.JSX.Element;

/** @category Layouts */
declare function Tabs(props: {
    children?: ViewNode;
    gap?: 0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10;
    hasDivider?: boolean;
    onChange?: (value: string) => void;
    value?: string;
}): React.JSX.Element;

/** @category Layouts @group Tabs */
declare function Tab(props: {
    children?: ViewNode;
    value: string;
    label: string;
    isDisabled?: boolean;
    panelId?: string;
}): React.JSX.Element;

/** @category Display */
declare function EmptyState(props: { title: string; isCompact?: boolean }): React.JSX.Element;

/** @category Display */
declare function Currency(props: { value: number; currency: string; locale?: string }): React.JSX.Element;

/** @category Display */
declare function Timestamp(props: {
    value: number | string;
    format?:
        | 'date'
        | 'date_long'
        | 'date_weekday'
        | 'date_time'
        | 'time'
        | 'relative'
        | 'system_date'
        | 'system_date_time'
        | 'system_time';
}): React.JSX.Element;

/** @category Display */
declare function Divider(props: {}): React.JSX.Element;

/** @category Display */
declare function MetadataList(props: {
    children?: ViewNode;
    columns?: 'multi' | 'single' | number;
    title?: ViewNode;
}): React.JSX.Element;

/** @category Display @group MetadataList */
declare function MetadataListItem(props: { children?: ViewNode; label: string; icon?: ViewNode }): React.JSX.Element;

/** @category Display @group Table */
type ColumnWidth = { type: 'proportional'; value: number; minWidth?: number } | { type: 'pixel'; value: number };

/** @category Display @group Table */
declare function proportional(
    value?: number,
    options?: { minWidth?: number },
): Extract<ColumnWidth, { type: 'proportional' }>;

/** @category Display @group Table */
declare function pixel(value: number): Extract<ColumnWidth, { type: 'pixel' }>;

/** @category Display */
declare function Table<T extends Record<string, unknown>>(props: {
    data: T[];
    idKey?: (keyof T & string) | ((row: T) => string | number);
    density?: 'compact' | 'balanced' | 'spacious';
    hasHover?: boolean;
    isStriped?: boolean;
    columns?: {
        key: string;
        header?: ViewNode;
        width?: ColumnWidth;
        align?: 'start' | 'center' | 'end';
        renderCell?: (row: T) => ViewNode;
    }[];
}): React.JSX.Element;
