// Generated by longlink dev from the installed SDK. Do not edit this local copy.
// Editor declarations only. The shared frontend supplies these APIs at runtime.
type ViewNode = React.JSX.Element | string | number | boolean | null | undefined | ViewNode[];
type ViewComponent<P> = (props: P & { children?: ViewNode }) => React.JSX.Element;
type Spacing = 0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10;

/** @category Runtime */
declare namespace React {
    namespace JSX {
        interface Element {
            readonly type: unknown;
            readonly props: unknown;
        }
        interface ElementChildrenAttribute {
            children: unknown;
        }
        interface IntrinsicElements {
            [name: string]: Record<string, unknown>;
        }
    }
}

/** @category Runtime */
declare function createElement(type: unknown, props: unknown, ...children: ViewNode[]): React.JSX.Element;
/** @category Runtime */
declare const Fragment: ViewComponent<{ key?: string | number }>;
/** @category Runtime */
declare function useState<T = undefined>(initial?: T | (() => T)): [T, (value: T | ((previous: T) => T)) => void];
/** @category Runtime */
declare function useEffect(effect: () => void | (() => void), dependencies?: readonly unknown[]): void;
/** @category Runtime */
declare function useMemo<T>(factory: () => T, dependencies: readonly unknown[]): T;
/** @category Runtime */
declare function useRef<T>(initial: T): { current: T };

/** @category Runtime */
declare const params: Readonly<Record<string, string>>;
/** @category Runtime */
declare function navigate(path: string): void;
/**
 * Requests a Solution operation; successful writes automatically refresh cached View data.
 * @category Runtime
 */
declare function request<T = unknown>(
    path: string,
    options?: {
        method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
        json?: unknown;
        form?: [string, string | Blob][];
        binary?: boolean;
    }
): Promise<T>;
/**
 * Returns defined data cached by path; the renderer handles initial loading, errors, and retry.
 * @category Runtime
 */
declare function useApi<T = unknown>(path: string): T;

/** @category Layouts */
declare const Stack: ViewComponent<{
    gap?: Spacing;
    direction?: 'horizontal' | 'vertical';
    justify?: 'start' | 'center' | 'end' | 'between' | 'around' | 'evenly';
    align?: 'start' | 'center' | 'end' | 'stretch';
    wrap?: 'nowrap' | 'wrap' | 'wrap-reverse';
    padding?: Spacing;
}>;
/** @category Content */
declare const Heading: ViewComponent<{ level?: 1 | 2 | 3 | 4 | 5 | 6 }>;
/** @category Content */
declare const Text: ViewComponent<{
    color?: 'primary' | 'secondary';
    type?: 'body' | 'large' | 'label' | 'supporting' | 'code';
}>;
/** @category Actions */
declare const Button: ViewComponent<{
    label: string;
    variant?: 'primary' | 'secondary' | 'ghost' | 'destructive';
    isDisabled?: boolean;
    clickAction?: () => void | Promise<void>;
}>;
/** @category Actions */
declare const IconButton: ViewComponent<{ icon: ViewNode; label: string; onClick?: () => void }>;
/** @category Actions */
declare const Link: ViewComponent<{ to: string }>;
/** @category Content */
declare const Badge: ViewComponent<{ label?: string; variant?: 'neutral' | 'info' | 'success' | 'warning' | 'error' }>;
/** @category Content */
declare const Avatar: ViewComponent<{ name?: string; src?: string; alt?: string }>;
/** @category Layouts */
declare const Dialog: ViewComponent<{
    'aria-label': string;
    isOpen: boolean;
    onOpenChange: (open: boolean) => void;
    purpose?: 'form' | 'info' | 'required';
}>;
/** @category Form */
declare const TextInput: ViewComponent<{
    label: string;
    value?: string;
    placeholder?: string;
    isRequired?: boolean;
    onChange?: (value: string) => void;
}>;
/** @category Form */
declare const TextArea: typeof TextInput;
/** @category Form */
declare const NumberInput: ViewComponent<{
    label: string;
    value?: number;
    min?: number;
    max?: number;
    step?: number;
    onChange?: (value: number | undefined) => void;
}>;
/** @category Form */
declare const Selector: ViewComponent<{
    label?: string;
    value?: string;
    options: { value: string; label: string }[];
    onChange?: (value: string | undefined) => void;
}>;
/** @category Form */
declare const FileInput: ViewComponent<{
    label: string;
    value?: File | null;
    accept?: string;
    onChange?: (value: File | null) => void;
}>;
/** @category Content */
declare const FileViewer: ViewComponent<{ src: string; title: string }>;
/** @category Layouts */
declare const Grid: ViewComponent<{ columns?: number; gap?: Spacing }>;
/** @category Layouts */
declare const GridSpan: ViewComponent<{ columns?: number | 'full' }>;
/** @category Layouts */
declare const StackItem: ViewComponent<{
    size?: 'static' | 'fill';
    isScrollable?: boolean;
    crossAlignSelf?: 'start' | 'center' | 'end' | 'stretch';
}>;
/** @category Layouts */
declare const Card: ViewComponent<{ padding?: Spacing; elevation?: 'none' | 'low' | 'medium' | 'high' }>;
/** @category Form */
declare const CheckboxInput: ViewComponent<{ label: string; value: boolean; onChange?: (value: boolean) => void }>;
/** @category Form */
declare const Switch: typeof CheckboxInput;
/** @category Form */
declare const Slider: ViewComponent<{
    label: string;
    value: number;
    min?: number;
    max?: number;
    step?: number;
    onChange?: (value: number) => void;
}>;
/** @category Form */
declare const RadioList: ViewComponent<{ label?: string; value?: string; onChange?: (value: string) => void }>;
/** @category Form */
declare const RadioListItem: ViewComponent<{ label: string; value: string }>;
/** @category Actions */
declare const MoreMenu: ViewComponent<{ items: { label: string; onClick: () => void; variant?: 'destructive' }[] }>;
/** @category Layouts */
declare const Menu: ViewComponent<{
    sections: { title: string; entries: { kind: 'item'; id: string; label: string; content: ViewNode }[] }[];
    gap?: Spacing;
}>;
/** @category Content */
declare const Icon: ViewComponent<{ icon: string; size: 'sm' | 'md' | 'lg' }>;
/** @category Content */
declare const CodeBlock: ViewComponent<{ code: string; language?: string; title?: string; isWrapped?: boolean }>;
/** @category Display */
declare const ProgressBar: ViewComponent<{ label?: string; value: number; max?: number; hasValueLabel?: boolean }>;
/** @category Layouts */
declare const Stepper: ViewComponent<{ activeStep?: number; orientation?: 'horizontal' | 'vertical' }>;
/** @category Layouts */
declare const Step: ViewComponent<{ step: number; label: string }>;
/** @category Layouts */
declare const TabList: ViewComponent<{ value?: string; onChange?: (value: string) => void }>;
/** @category Layouts */
declare const Tab: ViewComponent<{ value: string; label: string }>;
/** @category Display */
declare const StatusBadge: ViewComponent<{ status: 'running' | 'creating' | 'failed' }>;
/** @category Content */
declare const EmptyState: ViewComponent<{ title: string; isCompact?: boolean }>;
/** @category Display */
declare const Currency: ViewComponent<{ value: number; currency: string; locale?: string }>;
/** @category Display */
declare const Timestamp: ViewComponent<{ value: number | string; format?: string }>;
/** @category Content */
declare const Divider: ViewComponent<Record<string, never>>;
/** @category Content */
declare const Spinner: ViewComponent<{ label?: string }>;
/** @category Content */
declare const Banner: ViewComponent<{ status?: 'error' | 'warning' | 'success' | 'info'; title: string }>;
/** @category Layouts */
declare function Table<T>(props: {
    data: readonly T[];
    idKey?: string | ((row: T) => string | number);
    density?: 'compact' | 'comfortable';
    columns: { key: string; header?: string; align?: 'start' | 'center' | 'end'; renderCell: (row: T) => ViewNode }[];
}): React.JSX.Element;
