apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: csi-hostpathplugin
    namespace: default
spec:
    template:
        spec:
            containers:
                - name: csi-external-health-monitor-controller
                  $patch: delete
                - name: csi-resizer
                  $patch: delete
                - name: csi-snapshotter
                  $patch: delete
