# Template for the optional per-cluster Envoy gateway TLS secret.

---
apiVersion: v1
kind: Secret
metadata:
  name: $gateway_tls_secret_name
  namespace: $gateway_namespace
  labels:
    managed-by: longlink
    app: $gateway_name
type: kubernetes.io/tls
data:
  tls.crt: "$gateway_tls_certificate"
  tls.key: "$gateway_tls_key"
