import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { XMLParser, XMLValidator } from 'fast-xml-parser';
import { readFile, readdir, writeFile } from 'node:fs/promises';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const adaptersDirectory = path.resolve(root, '../sdk/longlink/.static/xsd/adapters');
const outputPath = path.resolve(root, 'src/lib/generated/documentation.ts');
const parser = new XMLParser({ attributeNamePrefix: '', ignoreAttributes: false });

/** Returns entries consistently whether XMLParser produced a singleton or array. */
function entries(value) {
    return Array.isArray(value) ? value : value === undefined ? [] : [value];
}

/** Reads documented component slugs from the SDK's XSD source contracts. */
async function componentSlugs() {
    const filenames = await readdir(adaptersDirectory);
    const slugs = [];

    for (const filename of filenames.sort()) {
        if (!filename.endsWith('.xsd')) {
            continue;
        }

        const source = await readFile(path.join(adaptersDirectory, filename), 'utf8');
        const validation = XMLValidator.validate(source);
        if (validation !== true) {
            throw new Error(`Invalid XML in ${filename}: ${validation.err.msg}`);
        }

        const schema = parser.parse(source)['xsd:schema'];
        for (const element of entries(schema?.['xsd:element'])) {
            const annotation = entries(element?.['xsd:annotation'])[0];
            const appInfo = entries(annotation?.['xsd:appinfo'])[0];
            const documentation = entries(appInfo?.['longlink:docs'])[0];

            if (typeof documentation?.slug === 'string') {
                slugs.push(documentation.slug);
            }
        }
    }

    const uniqueSlugs = new Set(slugs);
    if (uniqueSlugs.size !== slugs.length) {
        throw new Error('Documented component slugs must be unique.');
    }

    return slugs;
}

const slugs = await componentSlugs();
const values = slugs.map((slug) => `    '${slug}',`).join('\n');
const output = `// Generated by scripts/documentation.mjs from SDK XSD documentation metadata.\nexport const componentDocumentationSlugs = [\n${values}\n] as const;\n`;
const current = await readFile(outputPath, 'utf8').catch(() => undefined);

if (current !== output) {
    await writeFile(outputPath, output, 'utf8');
}
