import path from 'node:path';
import ts from 'typescript';
import { fileURLToPath } from 'node:url';
import { mkdir, readFile, writeFile } from 'node:fs/promises';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const input = path.resolve(root, '../sdk/longlink/.static/new/src/views/frontend.d.ts');
const source = await readFile(input, 'utf8');
const document = ts.createSourceFile(input, source, ts.ScriptTarget.Latest, true);
const categories = {
    Runtime: ['React', 'params', 'request', 'navigate', 'useApi'],
    Actions: ['Button', 'IconButton', 'Link', 'MoreMenu'],
    Content: ['Heading', 'Text', 'Avatar', 'Badge', 'Icon', 'CodeBlock', 'Divider', 'FileViewer', 'Spinner', 'Banner', 'EmptyState'],
    Display: ['Currency', 'Timestamp', 'ProgressBar', 'StatusBadge'],
    Form: ['TextInput', 'TextArea', 'NumberInput', 'Selector', 'FileInput', 'CheckboxInput', 'Switch', 'Slider', 'RadioList', 'RadioListItem'],
    Layouts: ['Stack', 'StackItem', 'Grid', 'GridSpan', 'Table', 'Card', 'Menu', 'Dialog', 'Stepper', 'Step', 'TabList', 'Tab'],
};

// Use TypeScript's parser rather than maintaining another markup or declaration parser.
if (document.parseDiagnostics.length) {
    throw new Error(ts.flattenDiagnosticMessageText(document.parseDiagnostics[0].messageText, '\n'));
}
const components = document.statements.flatMap((statement) => {
    const declaration = ts.isVariableStatement(statement) ? statement.declarationList.declarations[0] : statement;
    if (!ts.isVariableDeclaration(declaration) && !ts.isFunctionDeclaration(declaration) && !ts.isModuleDeclaration(declaration)) return [];
    const name = declaration.name?.getText(document);
    if (!name) return [];
    const category = Object.keys(categories).find((category) => categories[category].includes(name));
    if (!category) throw new Error(`Missing documentation category: ${name}`);
    return [{
        name,
        category,
        declaration: statement.getText(document),
        description: category === 'Runtime' ? `${name} is supplied by the isolated LongLink renderer.` : `${name} accepts native JSX props in LongLink Views.`,
        lastUpdated: '2026-10-02',
        slug: name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase(),
    }];
}).sort((left, right) => left.name.localeCompare(right.name));

const definition = `export type ComponentDocumentation = {
    name: string;
    category: string;
    declaration: string;
    description: string;
    lastUpdated: string;
    slug: string;
};`;
const outputs = new Map([
    [path.join(root, 'src/lib/generated/documentation.ts'), `// Generated by scripts/documentation.mjs from SDK JSX editor declarations.\n${definition}\n\nexport const documentationCategories: { name: string }[] = ${JSON.stringify(Object.keys(categories).map((name) => ({ name })), null, 4)};\n\nexport const componentDocumentation: ComponentDocumentation[] = ${JSON.stringify(components, null, 4)};\n`],
    [path.resolve(root, '../sdk/longlink/.static/jsx/components.json'), `${JSON.stringify(components, null, 4)}\n`],
]);

// CLI and website documentation share one generated catalog; checking must not modify files.
for (const [filename, output] of outputs) {
    const current = await readFile(filename, 'utf8').catch(() => undefined);
    if (current === output) continue;
    if (process.argv.includes('--check')) {
        console.error(`Generated documentation is stale: ${filename}`);
        process.exitCode = 1;
    } else {
        await mkdir(path.dirname(filename), { recursive: true });
        await writeFile(filename, output, 'utf8');
    }
}
