from src import adapters
from fastapi import HTTPException
from src.utils import images
from src.models.metadata import LongLinkMetadata
from src.models.applications import ApplicationCreate
from src.database.models.storages import StorageRegistry


async def application_image_metadata(payload: ApplicationCreate) -> LongLinkMetadata:
    """Inspect image metadata and validate required environment values."""

    reserved_payload = sorted(name for name in payload.envs if name.startswith("LONGLINK_"))

    # User payloads cannot provide values reserved for platform injection.
    if reserved_payload:
        raise HTTPException(status_code=409, detail=f"Reserved platform environment variables: {', '.join(reserved_payload)}")

    # Image inspection must succeed before the platform can trust runtime metadata.
    metadata = await images.metadata(payload.image)
    if metadata is None:
        raise HTTPException(status_code=409, detail="Image metadata could not be inspected")

    # Deployments must use a resolved immutable image reference.
    if metadata.digest is None or metadata.image is None:
        raise HTTPException(status_code=409, detail="Image digest could not be resolved")

    # LongLink-prefixed values are always injected by the LongLink Platform, never declared by applications.
    reserved_image: list[str] = []
    missing: list[str] = []

    # Walk required metadata envs once and split them by validation outcome.
    for env in metadata.environments:

        # Optional envs do not need payload or platform guarantees.
        if not env.required:
            continue

        # Runtime values with the platform prefix are injected later by the LongLink Platform.
        if env.name.startswith("LONGLINK_"):
            reserved_image.append(env.name)
            continue

        # Non-platform required values must be supplied by the application creation payload.
        if not payload.envs.get(env.name, "").strip():
            missing.append(env.name)

    reserved_image.sort()

    # Reject images that try to declare LongLink-managed runtime values.
    if reserved_image:
        raise HTTPException(status_code=409, detail=f"Reserved platform environment variables: {', '.join(reserved_image)}")

    missing.sort()

    # Reject images whose app-managed required values are absent.
    if missing:
        raise HTTPException(status_code=409, detail=f"Missing required environment variables: {', '.join(missing)}")

    return metadata


def runtime_environment(
    database_schema: str,
    connection: adapters.DatabaseRuntimeConnection,
    storage: StorageRegistry | None,
    bucket: str | None = None,
    shared: str | None = None,
    credentials: adapters.StorageRuntimeCredentials | None = None,
) -> dict[str, str]:
    """Build platform-managed environment variables for an application runtime."""

    # Build injected platform values explicitly so env names are visible at the injection point.
    envs = {
        "LONGLINK_ENV": "production",
        "LONGLINK_DATABASE_HOST": connection["host"],
        "LONGLINK_DATABASE_NAME": connection["database_name"],
        "LONGLINK_DATABASE_PASSWORD": connection["password"],
        "LONGLINK_DATABASE_PORT": str(connection["port"]),
        "LONGLINK_DATABASE_SCHEMA": database_schema,
        "LONGLINK_DATABASE_USERNAME": connection["username"],
    }

    # Add object storage values only when this application has storage configured.
    if storage is not None:

        # Storage credentials are generated by the storage adapter when storage is configured.
        if credentials is None:
            raise ValueError("Storage runtime credentials are required when storage is configured")

        # Bucket names are assigned by the LongLink Platform before runtime provisioning.
        if bucket is None or shared is None:
            raise ValueError("Assigned storage buckets are required when storage is configured")

        envs.update(
            {
                "LONGLINK_STORAGE_BUCKET": bucket,
                "LONGLINK_STORAGE_ENDPOINT_URL": storage.runtime_endpoint_url or storage.endpoint_url,
                "LONGLINK_STORAGE_PASSWORD": credentials["secret_access_key"],
                "LONGLINK_STORAGE_SHARED_BUCKET": shared,
                "LONGLINK_STORAGE_USERNAME": credentials["access_key_id"],
            }
        )

    return envs
