apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../../../k8s/operators/rook
patches:
    - target:
          kind: ConfigMap
          name: rook-ceph-operator-config
      patch: |-
          - op: replace
            path: /data/ROOK_CEPH_ALLOW_LOOP_DEVICES
            value: "true"
