apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../../k8s/infrastructure
patches:
    - target:
          kind: CephCluster
          name: rook-ceph
      patch: |-
          - op: replace
            path: /spec/mon/count
            value: 1
          - op: replace
            path: /spec/mon/volumeClaimTemplate/spec/storageClassName
            value: longlink-development
          - op: replace
            path: /spec/mon/volumeClaimTemplate/spec/resources/requests/storage
            value: 1Gi
          - op: replace
            path: /spec/mgr/count
            value: 1
          - op: replace
            path: /spec/storage/storageClassDeviceSets/0/count
            value: 1
          - op: replace
            path: /spec/storage/storageClassDeviceSets/0/volumeClaimTemplates/0/spec/storageClassName
            value: longlink-development
          - op: replace
            path: /spec/storage/storageClassDeviceSets/0/volumeClaimTemplates/0/spec/resources/requests/storage
            value: 1Gi
    - target:
          kind: CephObjectStore
          name: longlink
      patch: |-
          - op: replace
            path: /spec/metadataPool/replicated/size
            value: 1
          - op: replace
            path: /spec/metadataPool/replicated/requireSafeReplicaSize
            value: false
          - op: replace
            path: /spec/dataPool/replicated/size
            value: 1
          - op: replace
            path: /spec/dataPool/replicated/requireSafeReplicaSize
            value: false
          - op: replace
            path: /spec/gateway/instances
            value: 1
