export const documentationComponentSlugs = [
    'action',
    'avatar',
    'badge',
    'bindings',
    'button',
    'card',
    'checkbox-input',
    'dialog',
    'divider',
    'expressions',
    'file-input',
    'for',
    'grid',
    'heading',
    'icon',
    'link',
    'menu',
    'number-input',
    'query',
    'radio-list',
    'selector',
    'slider',
    'stack',
    'state',
    'switch',
    'tabs',
    'table',
    'text',
    'text-area',
    'text-input',
] as const;

export const documentationPaths = [
    '/docs',
    '/docs/api',
    '/docs/api/organizations',
    '/docs/api/solutions',
    '/docs/sdk',
    '/docs/sdk/environments',
    '/docs/sdk/routes',
    '/docs/sdk/storage',
    '/docs/sdk/database',
    '/docs/sdk/views',
    ...documentationComponentSlugs.map((slug) => `/docs/sdk/views/${slug}`),
    '/docs/sdk/testing',
    '/docs/sdk/building',
];
