import { adminPages } from './navigation';
import { index, layout, prefix, route, type RouteConfig } from '@react-router/dev/routes';

export default [
    layout('./layouts/Page.tsx', [index('./routes/Index.tsx'), route('pricing', './routes/Pricing.tsx')]),
    layout('./layouts/UseCases.tsx', [
        ...prefix('use-cases', [
            index('./routes/usecases/Introduction.tsx'),
            route('approvals-and-decisions', './routes/usecases/Approvals.tsx'),
            route('operations', './routes/usecases/Operations.tsx'),
            route('compliance-and-quality', './routes/usecases/Compliance.tsx'),
            route('cases-and-projects', './routes/usecases/Cases.tsx'),
            route('*', '../components/layouts/NotFound.tsx', { id: 'use-cases-not-found' }),
        ]),
        ...prefix('compare', [
            route('longlink-vs-retool', './routes/compare/Retool.tsx'),
            route('longlink-vs-lovable', './routes/compare/Lovable.tsx'),
            route('longlink-vs-windmill', './routes/compare/Windmill.tsx'),
            route('longlink-vs-microsoft-power-apps', './routes/compare/PowerApps.tsx'),
            route('longlink-vs-replit', './routes/compare/Replit.tsx'),
            route('longlink-vs-appsmith', './routes/compare/Appsmith.tsx'),
            route('longlink-vs-superblocks', './routes/compare/Superblocks.tsx'),
            route('longlink-vs-fastapi', './routes/compare/FastAPI.tsx'),
            route('longlink-vs-reflex', './routes/compare/Reflex.tsx'),
            route('*', '../components/layouts/NotFound.tsx', { id: 'compare-not-found' }),
        ]),
    ]),
    ...prefix('docs', [
        layout('./layouts/Documentation.tsx', [
            index('./routes/docs/Index.tsx'),
            route('introduction', './routes/docs/Introduction.tsx'),
            ...prefix('sdk', [
                index('./routes/docs/sdk/Index.tsx'),
                route('building', './routes/docs/sdk/Building.tsx'),
                route('database', './routes/docs/sdk/Database.tsx'),
                route('environments', './routes/docs/sdk/Environments.tsx'),
                route('routes', './routes/docs/sdk/Routes.tsx'),
                route('storage', './routes/docs/sdk/Storage.tsx'),
                route('testing', './routes/docs/sdk/Testing.tsx'),
                ...prefix('views', [
                    index('./routes/docs/sdk/Views.tsx'),
                    route('avatar', './routes/docs/sdk/views/Avatar.tsx'),
                    route('badge', './routes/docs/sdk/views/Badge.tsx'),
                    route('buttons', './routes/docs/sdk/views/Buttons.tsx'),
                    route('card', './routes/docs/sdk/views/Card.tsx'),
                    route('checkbox-input', './routes/docs/sdk/views/CheckboxInput.tsx'),
                    route('code-block', './routes/docs/sdk/views/CodeBlock.tsx'),
                    route('collapsible', './routes/docs/sdk/views/Collapsible.tsx'),
                    route('currency', './routes/docs/sdk/views/Currency.tsx'),
                    route('date-input', './routes/docs/sdk/views/DateInput.tsx'),
                    route('date-range-input', './routes/docs/sdk/views/DateRangeInput.tsx'),
                    route('date-time-input', './routes/docs/sdk/views/DateTimeInput.tsx'),
                    route('dialog', './routes/docs/sdk/views/Dialog.tsx'),
                    route('divider', './routes/docs/sdk/views/Divider.tsx'),
                    route('dropdown-menu', './routes/docs/sdk/views/DropdownMenu.tsx'),
                    route('empty-state', './routes/docs/sdk/views/EmptyState.tsx'),
                    route('file-input', './routes/docs/sdk/views/FileInput.tsx'),
                    route('file-viewer', './routes/docs/sdk/views/FileViewer.tsx'),
                    route('grid', './routes/docs/sdk/views/Grid.tsx'),
                    route('heading', './routes/docs/sdk/views/Heading.tsx'),
                    route('icon', './routes/docs/sdk/views/Icon.tsx'),
                    route('icon-button', './routes/docs/sdk/views/IconButton.tsx'),
                    route('link', './routes/docs/sdk/views/Link.tsx'),
                    route('menu', './routes/docs/sdk/views/Menu.tsx'),
                    route('metadata-list', './routes/docs/sdk/views/MetadataList.tsx'),
                    route('more-menu', './routes/docs/sdk/views/MoreMenu.tsx'),
                    route('multi-selector', './routes/docs/sdk/views/MultiSelector.tsx'),
                    route('number-input', './routes/docs/sdk/views/NumberInput.tsx'),
                    route('progress-bar', './routes/docs/sdk/views/ProgressBar.tsx'),
                    route('radio-list', './routes/docs/sdk/views/RadioList.tsx'),
                    route('hooks', './routes/docs/sdk/views/Hooks.tsx'),
                    route('selector', './routes/docs/sdk/views/Selector.tsx'),
                    route('slider', './routes/docs/sdk/views/Slider.tsx'),
                    route('functions', './routes/docs/sdk/views/Functions.tsx'),
                    route('stack', './routes/docs/sdk/views/Stack.tsx'),
                    route('stepper', './routes/docs/sdk/views/Stepper.tsx'),
                    route('switch', './routes/docs/sdk/views/Switch.tsx'),
                    route('table', './routes/docs/sdk/views/Table.tsx'),
                    route('tabs', './routes/docs/sdk/views/Tabs.tsx'),
                    route('text', './routes/docs/sdk/views/Text.tsx'),
                    route('text-area', './routes/docs/sdk/views/TextArea.tsx'),
                    route('text-input', './routes/docs/sdk/views/TextInput.tsx'),
                    route('time-input', './routes/docs/sdk/views/TimeInput.tsx'),
                    route('timestamp', './routes/docs/sdk/views/Timestamp.tsx'),
                ]),
            ]),
            ...prefix('api', [index('./routes/docs/api/Index.tsx')]),
            route('*', '../components/layouts/NotFound.tsx', { id: 'docs-not-found' }),
        ]),
    ]),
    layout('./layouts/Legal.tsx', [
        route('terms', './routes/legal/Terms.tsx'),
        route('privacy', './routes/legal/Privacy.tsx'),
        route('impressum', './routes/legal/Impressum.tsx'),
        ...prefix('branding', [
            route('logo', './routes/branding/Logo.tsx'),
            route('values', './routes/branding/Values.tsx'),
            route('comunication', './routes/branding/Communication.tsx'),
        ]),
    ]),
    layout('./layouts/Brand.tsx', [
        ...prefix('auth', [
            route('register', './routes/auth/Register.tsx'),
            route('verify-email', './routes/auth/VerifyEmail.tsx'),
            route('forgot-password', './routes/auth/ForgotPassword.tsx'),
            route('reset-password', './routes/auth/ResetPassword.tsx'),
        ]),
        route('login', './routes/auth/Login.tsx'),
        route('*', '../components/layouts/NotFound.tsx'),
    ]),
    layout('./layouts/Authenticated.tsx', [
        ...prefix('user', [
            layout('./layouts/User.tsx', [
                route('organizations', './routes/user/Organizations.tsx'),
                route('settings', './routes/user/Settings.tsx'),
            ]),
        ]),
        ...prefix('admin', [
            layout(
                './layouts/Admin.tsx',
                adminPages.map(({ id, path, module }) => route(path, module, { id }))
            ),
        ]),
        ...prefix('orgs/:organization', [
            layout('./layouts/Organization.tsx', [
                index('./routes/orgs/Organization.tsx'),
                route('settings', './routes/orgs/Settings.tsx'),
            ]),
            route('solutions/:solution/*', './routes/orgs/Solution.tsx'),
        ]),
    ]),
] satisfies RouteConfig;
