import { index, layout, prefix, route, type RouteConfig } from '@react-router/dev/routes';

export default [
    index('./routes/Index.tsx'),
    ...prefix('docs', [
        index('./routes/Docs/Index.tsx'),
        ...prefix('api', [
            index('./routes/Docs/Api/Index.tsx'),
            route('applications', './routes/Docs/Api/Applications.tsx'),
            route('organizations', './routes/Docs/Api/Organizations.tsx'),
        ]),
        ...prefix('sdk', [
            index('./routes/Docs/Sdk/Index.tsx'),
            route('building', './routes/Docs/Sdk/Building.tsx'),
            route('database', './routes/Docs/Sdk/Database.tsx'),
            route('environments', './routes/Docs/Sdk/Environments.tsx'),
            route('routes', './routes/Docs/Sdk/Routes.tsx'),
            route('storage', './routes/Docs/Sdk/Storage.tsx'),
            route('testing', './routes/Docs/Sdk/Testing.tsx'),
            ...prefix('pages', [
                index('./routes/Docs/Sdk/Pages.tsx'),
                route('action', './routes/Docs/Sdk/Pages/Action.tsx'),
                route('avatar', './routes/Docs/Sdk/Pages/Avatar.tsx'),
                route('badge', './routes/Docs/Sdk/Pages/Badge.tsx'),
                route('bindings', './routes/Docs/Sdk/Pages/Bindings.tsx'),
                route('button', './routes/Docs/Sdk/Pages/Button.tsx'),
                route('card', './routes/Docs/Sdk/Pages/Card.tsx'),
                route('checkbox-input', './routes/Docs/Sdk/Pages/CheckboxInput.tsx'),
                route('dialog', './routes/Docs/Sdk/Pages/Dialog.tsx'),
                route('divider', './routes/Docs/Sdk/Pages/Divider.tsx'),
                route('expressions', './routes/Docs/Sdk/Pages/Expressions.tsx'),
                route('file-input', './routes/Docs/Sdk/Pages/FileInput.tsx'),
                route('for', './routes/Docs/Sdk/Pages/For.tsx'),
                route('grid', './routes/Docs/Sdk/Pages/Grid.tsx'),
                route('heading', './routes/Docs/Sdk/Pages/Heading.tsx'),
                route('icon', './routes/Docs/Sdk/Pages/Icon.tsx'),
                route('if', './routes/Docs/Sdk/Pages/If.tsx'),
                route('link', './routes/Docs/Sdk/Pages/Link.tsx'),
                route('number-input', './routes/Docs/Sdk/Pages/NumberInput.tsx'),
                route('query', './routes/Docs/Sdk/Pages/Query.tsx'),
                route('radio-list', './routes/Docs/Sdk/Pages/RadioList.tsx'),
                route('radio-list-item', './routes/Docs/Sdk/Pages/RadioListItem.tsx'),
                route('selector', './routes/Docs/Sdk/Pages/Selector.tsx'),
                route('selector-option', './routes/Docs/Sdk/Pages/SelectorOption.tsx'),
                route('side-nav', './routes/Docs/Sdk/Pages/SideNav.tsx'),
                route('slider', './routes/Docs/Sdk/Pages/Slider.tsx'),
                route('stack', './routes/Docs/Sdk/Pages/Stack.tsx'),
                route('state', './routes/Docs/Sdk/Pages/State.tsx'),
                route('switch', './routes/Docs/Sdk/Pages/Switch.tsx'),
                route('tab', './routes/Docs/Sdk/Pages/Tab.tsx'),
                route('table', './routes/Docs/Sdk/Pages/Table.tsx'),
                route('text', './routes/Docs/Sdk/Pages/Text.tsx'),
                route('text-area', './routes/Docs/Sdk/Pages/TextArea.tsx'),
                route('text-input', './routes/Docs/Sdk/Pages/TextInput.tsx'),
            ]),
        ]),
        route('*', './NotFound.tsx', { id: 'docs-not-found' }),
    ]),
    route('terms', './routes/Legal/Terms.tsx'),
    route('privacy', './routes/Legal/Privacy.tsx'),
    route('impressum', './routes/Legal/Impressum.tsx'),
    route('pricing', './routes/Pricing.tsx'),
    route('marketplace', './routes/Marketplace.tsx'),
    ...prefix('auth', [
        route('register', './routes/Auth/Register.tsx'),
        route('verify-email', './routes/Auth/VerifyEmail.tsx'),
        route('forgot-password', './routes/Auth/ForgotPassword.tsx'),
        route('reset-password', './routes/Auth/ResetPassword.tsx'),
    ]),
    route('organizations', './routes/Organizations.tsx'),
    route('settings', './routes/Settings.tsx'),
    ...prefix('admin', [
        layout('./routes/Admin/Layout.tsx', [
            route('users', './routes/Admin/Users.tsx'),
            route('applications', './routes/Admin/Applications.tsx'),
            route('organizations', './routes/Admin/Organizations.tsx'),
            route('database', './routes/Admin/Database.tsx'),
            route('storage', './routes/Admin/Storage.tsx'),
            route('compute', './routes/Admin/Compute.tsx'),
            route('operations', './routes/Admin/Operations.tsx'),
        ]),
    ]),
    route('orgs/:organization', './routes/Orgs/Layout.tsx', [
        index('./routes/Orgs/Organization.tsx'),
        route('settings', './routes/Orgs/Settings.tsx'),
        route('apps/:application/*', './routes/Orgs/Application.tsx'),
    ]),
    route('*', './NotFound.tsx'),
] satisfies RouteConfig;
