apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
    name: longlink-health
    namespace: rook-ceph
spec:
    store: longlink
    quotas:
        maxBuckets: -1
    opMask:
        - read
