import sys
from alembic.config import Config
from collections.abc import Callable
from longlink.database import migrations as database_migrations
from alembic.operations.ops import UpgradeOps, DowngradeOps, MigrationScript
from longlink.database.base import User, database_metadata
from longlink.database.migrations import include_object, load_application_models


def test_migration_loader_discovers_nested_database_models(tmp_path, monkeypatch) -> None:
    """Load nested application model modules for Alembic metadata."""

    # Create a nested Application model in an isolated project tree.
    table_name = "nested_inventory_items"
    module_name = "src.database.models.inventory"
    model_path = tmp_path / "src" / "database" / "models" / "inventory.py"
    model_path.parent.mkdir(parents=True)
    model_path.write_text(
        "from longlink import Table\n"
        "from sqlmodel import Field\n"
        "\n\n"
        "class NestedInventoryItem(Table, table=True):\n"
        "    \"\"\"Nested inventory table.\"\"\"\n"
        "\n"
        f"    __tablename__ = \"{table_name}\"\n"
        "\n"
        "    id: int | None = Field(default=None, primary_key=True)\n",
        encoding="utf-8",
    )
    monkeypatch.chdir(tmp_path)

    # Load project models and verify their metadata registration.
    try:
        load_application_models()

        assert table_name in database_metadata.tables
    finally:

        # Remove global metadata and import state even if discovery fails.
        table = database_metadata.tables.get(table_name)
        if table is not None:
            database_metadata.remove(table)
        sys.modules.pop(module_name, None)


def test_database_migrations_exclude_shared_users_table() -> None:
    """Keep the platform-owned users table out of app migrations."""

    assert include_object(getattr(User, "__table__"), "users", "table", False, None) is False


def test_make_migrations_skips_empty_autogenerated_revisions(tmp_path, monkeypatch) -> None:
    """Skip writing Alembic revisions when autogenerate finds no schema changes."""

    # Isolate migration output and record Application model loading.
    captured: dict[str, object] = {}
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(database_migrations, "load_application_models", lambda: captured.setdefault("loaded", True))

    # Simulate Alembic returning an empty autogenerated revision.
    def fake_revision(
        _cfg: object,
        autogenerate: bool,
        process_revision_directives: Callable[[object, object, list[MigrationScript]], None],
    ) -> None:
        """Run the Alembic empty-revision callback with fake operations."""

        directives = [MigrationScript(None, UpgradeOps(), DowngradeOps())]
        process_revision_directives(object(), object(), directives)
        captured["autogenerate"] = autogenerate
        captured["directives"] = directives

    monkeypatch.setattr(database_migrations.command, "revision", fake_revision)

    # Generate migrations through the instrumented Alembic command.
    migration_created = database_migrations.make_migrations()

    # Verify no revision was written while its directory was initialized.
    assert migration_created is False
    assert captured["loaded"] is True
    assert captured["autogenerate"] is True
    assert captured["directives"] == []
    assert (tmp_path / "migrations").is_dir()


def test_apply_migrations_uses_application_migration_directory(tmp_path, monkeypatch) -> None:
    """Apply app migrations through the SDK Alembic environment and app migration directory."""

    # Isolate the project directory and capture Alembic configuration.
    captured: dict[str, object] = {}
    monkeypatch.chdir(tmp_path)

    def fake_upgrade(cfg: Config, revision: str) -> None:
        """Capture the Alembic upgrade config."""

        captured["script_location"] = cfg.get_main_option("script_location")
        captured["version_locations"] = cfg.get_main_option("version_locations")
        captured["revision"] = revision

    monkeypatch.setattr(database_migrations.command, "upgrade", fake_upgrade)

    # Apply migrations through the instrumented Alembic command.
    database_migrations.apply_migrations()

    # Verify the SDK environment targets the Application migration directory.
    assert captured["script_location"] == str(database_migrations.CURRENT_FILE.parent)
    assert captured["version_locations"] == str(tmp_path / "migrations")
    assert captured["revision"] == "head"
