import sys
import pytest
import sqlite3
from io import StringIO
from alembic import command
from pathlib import Path
from sqlmodel import SQLModel
from contextlib import closing
from sqlalchemy import create_engine
from alembic.config import Config
from longlink.database import migrations as database_migrations
from longlink.constants import ROOT


@pytest.mark.parametrize(
    ("name", "type_", "expected"),
    [
        pytest.param("audit", "table", False, id="shared-audit-table"),
        pytest.param("inventory", "table", True, id="solution-table"),
        pytest.param("audit", "index", True, id="audit-index"),
    ],
)
def test_include_object_excludes_only_platform_owned_audit_table(name: str, type_: str, expected: bool) -> None:
    """Keep Platform-owned audit tables out of Solution Alembic revisions."""

    # Act
    included = database_migrations.include_object(object(), name, type_, False, None)

    # Assert
    assert included is expected


def test_make_migrations_creates_revisions_only_for_schema_operations(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Discover nested models once and create revisions only for schema changes."""

    # Arrange
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("LONGLINK_ENV", "development")
    table_name = "autogenerated_inventory_items"
    module_name = "src.models.catalog.autogenerated_inventory"
    assert module_name not in sys.modules
    assert table_name not in SQLModel.metadata.tables

    # Match existing metadata without replacing or removing other tests' tables.
    engine = create_engine("sqlite:///dev.db")
    try:
        SQLModel.metadata.create_all(engine)
    finally:
        engine.dispose()

    # Discover one new nested Solution model through the real migration loader.
    model_path = tmp_path / "src" / "models" / "catalog" / "autogenerated_inventory.py"
    model_path.parent.mkdir(parents=True)
    model_path.write_text(
        "from sqlmodel import Field, SQLModel\n"
        "\n\n"
        "class AutogeneratedInventoryItem(SQLModel, table=True):\n"
        '    """Inventory table generated by Alembic."""\n'
        "\n"
        f'    __tablename__ = "{table_name}"\n'
        "\n"
        "    id: int | None = Field(default=None, primary_key=True)\n",
        encoding="utf-8",
    )

    try:
        # Act
        migration_created = database_migrations.make_migrations()

        # Assert
        assert migration_created is True
        revisions = list((tmp_path / "migrations").glob("*.py"))
        assert len(revisions) == 1

        # Apply the generated revision and verify its table through an independent connection.
        database_migrations.apply_migrations()
        with closing(sqlite3.connect(tmp_path / "dev.db")) as connection:
            tables = connection.execute("SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?", (table_name,)).fetchall()
        assert tables == [(table_name,)]

        # Suppress a second revision when the migrated schema already matches metadata.
        assert database_migrations.make_migrations() is False
        assert list((tmp_path / "migrations").glob("*.py")) == revisions
    finally:
        # Remove only this test's model metadata and module, including on migration failure.
        table = SQLModel.metadata.tables.get(table_name)
        if table is not None:
            SQLModel.metadata.remove(table)
        sys.modules.pop(module_name, None)


@pytest.mark.usefixtures("production_environment")
def test_production_migrations_rejects_missing_revisions_before_upgrade(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Fail production startup without committed Solution revisions."""

    # Arrange
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        database_migrations.command,
        "upgrade",
        lambda *_: pytest.fail("Alembic upgrade must not run without Solution migrations"),
    )

    # Act and assert
    with pytest.raises(RuntimeError, match="require migrations"):
        database_migrations.apply_migrations()


@pytest.mark.usefixtures("production_environment")
def test_production_migrations_upgrade_head_with_committed_revision(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Apply committed Solution revisions in production."""

    # Arrange
    migrations_path = tmp_path / "migrations"
    migrations_path.mkdir()
    migrations_path.joinpath("001_initial.py").write_text("", encoding="utf-8")
    captured: dict[str, Config | str] = {}
    monkeypatch.chdir(tmp_path)

    def upgrade(config: Config, target: str) -> None:
        """Capture the Alembic configuration and revision target."""

        captured["config"] = config
        captured["target"] = target

    monkeypatch.setattr(database_migrations.command, "upgrade", upgrade)

    # Act
    database_migrations.apply_migrations()

    # Assert
    config = captured["config"]
    assert isinstance(config, Config)
    assert captured["target"] == "head"
    assert config.get_main_option("script_location") == str(database_migrations.CURRENT_FILE.parent)
    assert config.get_main_option("version_locations") == str(migrations_path)


def test_migration_environment_emits_offline_sql_without_creating_database(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """Emit Solution migration SQL without opening a database connection."""

    # Arrange
    output = StringIO()
    config = database_migrations.migration_config(ROOT / ".static" / "new" / "migrations")
    config.output_buffer = output
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("LONGLINK_ENV", "development")

    # Act
    command.upgrade(config, "head", sql=True)

    # Assert
    sql = output.getvalue()
    assert "CREATE TABLE item (" in sql
    assert "INSERT INTO alembic_version" in sql
    assert not (tmp_path / "dev.db").exists()
