from enum import Enum


class Icon(str, Enum):
    """Lucide icon slugs supported by the web runtime."""

    ACTIVITY = "activity"
    ARROW_RIGHT = "arrow-right"
    BANKNOTE = "banknote"
    BELL = "bell"
    BOX = "box"
    BOXES = "boxes"
    BUILDING_2 = "building-2"
    CHECK = "check"
    CLIPBOARD_LIST = "clipboard-list"
    CONTAINER = "container"
    CPU = "cpu"
    DATABASE = "database"
    DOWNLOAD = "download"
    HARD_DRIVE = "hard-drive"
    LAYERS = "layers"
    LAYOUT_DASHBOARD = "layout-dashboard"
    LAYOUT_GRID = "layout-grid"
    LINK = "link"
    LIST = "list"
    LIST_CHECK = "list-check"
    MAP_PIN = "map-pin"
    PLUS = "plus"
    ROCKET = "rocket"
    ROTATE_CCW = "rotate-ccw"
    SETTINGS_2 = "settings-2"
    SHIELD_CHECK = "shield-check"
    SLIDERS_HORIZONTAL = "sliders-horizontal"
    TIMER = "timer"
    USERS = "users"
    X = "x"
