<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:include schemaLocation="../types.xsd" />
  <xsd:complexType name="ButtonType">
    <xsd:sequence><xsd:any minOccurs="0" maxOccurs="unbounded" processContents="lax" /></xsd:sequence>
    <xsd:attribute name="label" type="NonBlankStringType" use="required" />
    <xsd:attribute name="variant" type="ButtonVariantType" default="secondary" />
    <xsd:attribute name="size" type="SizeType" default="md" />
    <xsd:attribute name="type" type="ButtonHtmlType" default="button" />
    <xsd:attribute name="isDisabled" type="xsd:string" />
    <xsd:attribute name="isLoading" type="xsd:string" />
    <xsd:attribute name="isIconOnly" type="xsd:string" />
    <xsd:attribute name="tooltip" type="xsd:string" />
    <xsd:attribute name="elevation" type="ElevationType" />
    <xsd:attribute name="isInterruptible" type="xsd:boolean" />
    <xsd:attributeGroup ref="XmlRuntimeAttributes" />
  </xsd:complexType>
  <xsd:element name="Button" type="ButtonType">
    <xsd:annotation><xsd:documentation>Renders an Astryx action button.</xsd:documentation></xsd:annotation>
  </xsd:element>
</xsd:schema>
