<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:include schemaLocation="../types.xsd" />
  <xsd:complexType name="CheckboxInputType">
    <xsd:attribute name="label" type="NonBlankStringType" use="required" />
    <xsd:attribute name="value" type="xsd:string" />
    <xsd:attribute name="size" type="CompactSizeType" default="md" />
    <xsd:attribute name="description" type="xsd:string" />
    <xsd:attribute name="htmlName" type="xsd:string" />
    <xsd:attribute name="width" type="xsd:string" />
    <xsd:attribute name="disabledMessage" type="xsd:string" />
    <xsd:attribute name="status" type="InputStatusType" />
    <xsd:attribute name="statusMessage" type="xsd:string" />
    <xsd:attribute name="isDisabled" type="xsd:string" />
    <xsd:attribute name="isReadOnly" type="xsd:string" />
    <xsd:attribute name="isRequired" type="xsd:string" />
    <xsd:attribute name="isOptional" type="xsd:string" />
    <xsd:attribute name="isLabelHidden" type="xsd:string" />
    <xsd:attribute name="isLoading" type="xsd:boolean" />
    <xsd:attributeGroup ref="XmlRuntimeAttributes" />
  </xsd:complexType>
  <xsd:element name="CheckboxInput" type="CheckboxInputType">
    <xsd:annotation><xsd:documentation>Collects a boolean with an Astryx checkbox.</xsd:documentation></xsd:annotation>
  </xsd:element>
</xsd:schema>
