<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:include schemaLocation="../types.xsd" />
  <xsd:complexType name="LinkType">
    <xsd:sequence><xsd:any minOccurs="1" maxOccurs="unbounded" processContents="strict" /></xsd:sequence>
    <xsd:attribute name="href" type="xsd:string" />
    <xsd:attribute name="to" type="xsd:string" />
    <xsd:attribute name="isDisabled" type="xsd:string" />
    <xsd:attributeGroup ref="XmlRuntimeAttributes" />
  </xsd:complexType>
  <xsd:element name="Link" type="LinkType">
    <xsd:annotation><xsd:documentation>Renders a URL-safe Astryx link.</xsd:documentation></xsd:annotation>
  </xsd:element>
</xsd:schema>
