<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:longlink="urn:longlink:xsd-docs">
  <xsd:include schemaLocation="../types.xsd"/>
  <xsd:complexType name="LinkType" mixed="true">
    <xsd:sequence>
      <xsd:any minOccurs="0" maxOccurs="unbounded" processContents="strict"/>
    </xsd:sequence>
    <xsd:attribute name="href" type="xsd:string">
      <xsd:annotation>
        <xsd:documentation>External or absolute URL.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="to" type="xsd:string">
      <xsd:annotation>
        <xsd:documentation>Application-relative navigation destination.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="isDisabled" type="xsd:string">
      <xsd:annotation>
        <xsd:documentation>Disables the link.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attributeGroup ref="XmlRuntimeAttributes"/>
  </xsd:complexType>
  <xsd:element name="Link" type="LinkType">
    <xsd:annotation>
      <xsd:documentation>A styled anchor for inline and standalone text navigation. Inside Action, it can follow requests and patches as the terminal navigation step.</xsd:documentation>
      <xsd:appinfo source="urn:longlink:xml-example">
        <longlink:example>&lt;Link to="/orders/${order.id}"&gt;Open order&lt;/Link&gt;

&lt;Action&gt;
  &lt;Request method="POST" url="/api/orders" json="${order}" /&gt;
  &lt;Link to="/orders/${order.id}"&gt;Create and open order&lt;/Link&gt;
&lt;/Action&gt;</longlink:example>
      </xsd:appinfo>
    </xsd:annotation>
  </xsd:element>
</xsd:schema>
