<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:longlink="urn:longlink:xsd-docs">
  <xsd:complexType name="MenuType">
    <xsd:sequence>
      <xsd:element ref="MenuSection" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="gap" type="SpacingType" default="3">
      <xsd:annotation>
        <xsd:documentation>Space between selected menu content elements.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attributeGroup ref="XmlRuntimeAttributes"/>
  </xsd:complexType>
  <xsd:complexType name="MenuSectionType">
    <xsd:sequence>
      <xsd:choice minOccurs="1" maxOccurs="unbounded">
        <xsd:element ref="MenuItem"/>
        <xsd:element ref="MenuSubSection"/>
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="title" type="NonBlankStringType" use="required">
      <xsd:annotation>
        <xsd:documentation>Sets the title property.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="isHeaderHidden" type="xsd:string"/>
    <xsd:attributeGroup ref="XmlRuntimeAttributes"/>
  </xsd:complexType>
  <xsd:complexType name="MenuItemType">
    <xsd:sequence>
      <xsd:any minOccurs="0" maxOccurs="unbounded" processContents="strict"/>
    </xsd:sequence>
    <xsd:attribute name="label" type="NonBlankStringType" use="required">
      <xsd:annotation>
        <xsd:documentation>Accessible label.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="icon" type="xsd:string"/>
    <xsd:attributeGroup ref="XmlRuntimeAttributes"/>
  </xsd:complexType>
  <xsd:complexType name="MenuSubSectionType">
    <xsd:sequence>
      <xsd:element ref="MenuItem" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="label" type="NonBlankStringType" use="required">
      <xsd:annotation>
        <xsd:documentation>Accessible label.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="icon" type="xsd:string"/>
    <xsd:attributeGroup ref="XmlRuntimeAttributes"/>
  </xsd:complexType>
  <xsd:element name="Menu" type="MenuType">
    <xsd:annotation>
      <xsd:documentation>Renders hash-selected application sections in the shared menu layout.</xsd:documentation>
      <xsd:appinfo source="urn:longlink:xml-example">
        <longlink:docs slug="menu" category="Layout" lastUpdated="2026-08-19" source="adapters/Menu.xsd"/>
        <longlink:example>&lt;Menu&gt;
  &lt;MenuSection title="Settings"&gt;
    &lt;MenuItem label="General" icon="viewColumns"&gt;
      &lt;Heading level="2"&gt;General&lt;/Heading&gt;
    &lt;/MenuItem&gt;
    &lt;MenuItem label="Workflow" icon="arrowsUpDown"&gt;
      &lt;Heading level="2"&gt;Workflow&lt;/Heading&gt;
    &lt;/MenuItem&gt;
  &lt;/MenuSection&gt;
&lt;/Menu&gt;</longlink:example>
      </xsd:appinfo>
    </xsd:annotation>
  </xsd:element>
  <xsd:element name="MenuSection" type="MenuSectionType"/>
  <xsd:element name="MenuItem" type="MenuItemType"/>
  <xsd:element name="MenuSubSection" type="MenuSubSectionType"/>
</xsd:schema>
