<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:longlink="urn:longlink:xsd-docs">
  <xsd:complexType name="QueryType">
    <xsd:attribute name="id" type="xsd:string" use="required">
      <xsd:annotation>
        <xsd:documentation>Literal runtime identifier.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="path" type="xsd:string" use="required">
      <xsd:annotation>
        <xsd:documentation>Solution-relative JSON endpoint path.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attributeGroup ref="XmlRuntimeAttributes"/>
  </xsd:complexType>
  <xsd:element name="Query" type="QueryType">
    <xsd:annotation>
      <xsd:documentation>Use Query to bring the information a Solution View needs into scope, such as a list of orders or customer details.</xsd:documentation>
      <xsd:appinfo source="urn:longlink:xml-example">
        <longlink:docs slug="query" category="State" lastUpdated="2026-07-21" source="adapters/Query.xsd"/>
        <longlink:example>&lt;Query id="orders" path="/api/orders" /&gt;</longlink:example>
      </xsd:appinfo>
    </xsd:annotation>
  </xsd:element>
</xsd:schema>
