<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:longlink="urn:longlink:xsd-docs">
  <xsd:complexType name="SelectorType">
    <xsd:sequence>
      <xsd:element ref="Option" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="label" type="NonBlankStringType" use="required">
      <xsd:annotation>
        <xsd:documentation>Visible field label.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="value" type="xsd:string">
      <xsd:annotation>
        <xsd:documentation>Selected option value.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attributeGroup ref="XmlRuntimeAttributes"/>
  </xsd:complexType>
  <xsd:element name="Selector" type="SelectorType">
    <xsd:annotation>
      <xsd:documentation>A dropdown selector for choosing a single value from a list of options. Use it in forms and settings when presenting a moderate number of options.</xsd:documentation>
      <xsd:appinfo source="urn:longlink:xml-example">
        <longlink:docs slug="selector" category="Form" lastUpdated="2026-07-21" source="adapters/Selector.xsd"/>
        <longlink:example>&lt;Selector label="Status" value="$filters.status"&gt;
  &lt;Option value="open" label="Open" /&gt;
  &lt;Option value="closed" label="Closed" /&gt;
&lt;/Selector&gt;</longlink:example>
      </xsd:appinfo>
    </xsd:annotation>
  </xsd:element>
</xsd:schema>
