<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:longlink="urn:longlink:xsd-docs">
  <xsd:complexType name="CreateSolutionType">
    <xsd:attribute name="organizationId" type="xsd:string" use="required"/>
    <xsd:attributeGroup ref="XmlRuntimeAttributes"/>
  </xsd:complexType>
  <xsd:complexType name="SolutionUpdateType">
    <xsd:attribute name="organizationId" type="xsd:string" use="required"/>
    <xsd:attribute name="solution" type="xsd:string" use="required"/>
    <xsd:attributeGroup ref="XmlRuntimeAttributes"/>
  </xsd:complexType>
  <xsd:complexType name="SolutionLogsType">
    <xsd:attribute name="solutionId" type="xsd:string" use="required"/>
    <xsd:attributeGroup ref="XmlRuntimeAttributes"/>
  </xsd:complexType>
  <xsd:element name="CreateSolution" type="CreateSolutionType"/>
  <xsd:element name="SolutionUpdate" type="SolutionUpdateType"/>
  <xsd:element name="SolutionLogs" type="SolutionLogsType"/>
</xsd:schema>
