<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:longlink="urn:longlink:xsd-docs">
  <xsd:include schemaLocation="../types.xsd"/>
  <xsd:complexType name="StackItemType" mixed="true">
    <xsd:sequence>
      <xsd:any minOccurs="0" maxOccurs="unbounded" processContents="strict"/>
    </xsd:sequence>
    <xsd:attribute name="size" type="StackItemSizeType" default="static">
      <xsd:annotation>
        <xsd:documentation>Component size.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="isScrollable" type="xsd:boolean" default="false">
      <xsd:annotation>
        <xsd:documentation>Sets the isScrollable property.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="crossAlignSelf" type="BoxAlignType">
      <xsd:annotation>
        <xsd:documentation>Sets the crossAlignSelf property.</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attributeGroup ref="XmlRuntimeAttributes"/>
  </xsd:complexType>
  <xsd:element name="StackItem" type="StackItemType">
    <xsd:annotation>
      <xsd:documentation>Stack arranges items in a row or column with consistent spacing. Use StackItem when an individual child needs to fill available space, scroll, or override cross-axis alignment.</xsd:documentation>
      <xsd:appinfo source="urn:longlink:xml-example">
        <longlink:example><![CDATA[<Stack direction="horizontal" align="center">
  $order.number
  <StackItem size="fill">Order details</StackItem>
  <Button>Open</Button>
</Stack>]]></longlink:example>
      </xsd:appinfo>
    </xsd:annotation>
  </xsd:element>
</xsd:schema>
