<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:include schemaLocation="../types.xsd" />
  <xsd:complexType name="StackType">
    <xsd:sequence><xsd:any minOccurs="0" maxOccurs="unbounded" processContents="strict" /></xsd:sequence>
    <xsd:attribute name="direction" type="OrientationType" default="vertical" />
    <xsd:attribute name="justify" type="StackJustifyType" default="start" />
    <xsd:attribute name="align" type="BoxAlignType" default="stretch" />
    <xsd:attribute name="wrap" type="StackWrapType" default="nowrap" />
    <xsd:attributeGroup ref="XmlRuntimeAttributes" />
  </xsd:complexType>
  <xsd:element name="Stack" type="StackType">
    <xsd:annotation><xsd:documentation>Arranges XML children with Astryx Stack.</xsd:documentation></xsd:annotation>
  </xsd:element>
</xsd:schema>
