<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:include schemaLocation="../types.xsd" />
  <xsd:complexType name="TextType">
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="as" type="TextElementType" />
    <xsd:attribute name="type" type="TypographyType" />
    <xsd:attribute name="size" type="TextSizeType" />
    <xsd:attribute name="color" type="TextColorType" />
    <xsd:attribute name="value" type="xsd:string" use="required" />
    <xsd:attribute name="weight" type="FontWeightType" />
    <xsd:attribute name="display" type="TextDisplayType" />
    <xsd:attribute name="justify" type="AlignType" />
    <xsd:attribute name="maxLines" type="xsd:nonNegativeInteger" />
    <xsd:attribute name="textWrap" type="TextWrapType" />
    <xsd:attribute name="wordBreak" type="WordBreakType" />
    <xsd:attribute name="hasCapsize" type="xsd:boolean" />
    <xsd:attribute name="hasStrikethrough" type="xsd:boolean" />
    <xsd:attribute name="hasTabularNumbers" type="xsd:boolean" />
    <xsd:attribute name="hasTruncateTooltip" type="TruncateTooltipType" />
    <xsd:attributeGroup ref="XmlRuntimeAttributes" />
  </xsd:complexType>
  <xsd:element name="Text" type="TextType">
    <xsd:annotation><xsd:documentation>Renders semantic Astryx text.</xsd:documentation></xsd:annotation>
  </xsd:element>
</xsd:schema>
