<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:include schemaLocation="../types.xsd" />
  <xsd:complexType name="TextAreaType">
    <xsd:attribute name="label" type="NonBlankStringType" use="required" />
    <xsd:attribute name="value" type="xsd:string" />
    <xsd:attribute name="description" type="xsd:string" />
    <xsd:attribute name="rows" type="xsd:positiveInteger" />
    <xsd:attribute name="maxLength" type="xsd:nonNegativeInteger" />
    <xsd:attribute name="isDisabled" type="xsd:string" />
    <xsd:attribute name="isRequired" type="xsd:string" />
    <xsd:attributeGroup ref="XmlRuntimeAttributes" />
  </xsd:complexType>
  <xsd:element name="TextArea" type="TextAreaType">
    <xsd:annotation><xsd:documentation>Collects multi-line text with an accessible Astryx field.</xsd:documentation></xsd:annotation>
  </xsd:element>
</xsd:schema>
