import type { ComponentType } from 'react';
import type { Props } from '../types';
import {
    Action,
    Avatar,
    Badge,
    Banner,
    Button,
    ButtonGroup,
    Card,
    CheckboxInput,
    Code,
    Dialog,
    Divider,
    FileInput,
    FormLayout,
    Grid,
    Heading,
    Icon,
    Link,
    Longlink,
    NumberInput,
    RadioList,
    RadioListItem,
    Selector,
    SelectorOption,
    Slider,
    Stack,
    Switch,
    Tab,
    TabList,
    Table,
    TableColumn,
    Text,
    TextArea,
    TextInput,
} from '../adapters';

/** Explicit XML v2 tag-to-adapter registry. */
export const xmlComponentRegistry: Record<string, ComponentType<Props>> = {
    longlink: Longlink,
    Action,
    Avatar,
    Badge,
    Banner,
    Button,
    ButtonGroup,
    Card,
    CheckboxInput,
    Code,
    Dialog,
    Divider,
    FileInput,
    FormLayout,
    Grid,
    Heading,
    Icon,
    Link,
    NumberInput,
    RadioList,
    RadioListItem,
    Selector,
    SelectorOption,
    Slider,
    Stack,
    Switch,
    Tab,
    TabList,
    Table,
    TableColumn,
    Text,
    TextArea,
    TextInput,
};
