{{- $secretName := .Values.rustfs.secret.existingSecret }}
{{- $existingSecret := lookup "v1" "Secret" "rustfs" $secretName }}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ $secretName }}
    namespace: rustfs
    annotations:
        helm.sh/resource-policy: keep
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: {{ .Values.rustfs.secret.accessKey | default (randAlphaNum 20) | quote }}
    RUSTFS_SECRET_KEY: {{ .Values.rustfs.secret.secretKey | default (randAlphaNum 32) | quote }}
{{- end }}
