apiVersion: v2
name: longlink-compute
description: Shared LongLink Compute infrastructure.
type: application
version: 0.1.0
appVersion: v0.0.0
dependencies:
    - name: cloudnative-pg
      version: 0.28.1
      repository: file://charts/cloudnative-pg
    - name: rustfs
      version: 1.0.0
      repository: file://charts/rustfs
