gateway:
    address: 127.0.0.1
    service:
        nodePort: 30443
        type: NodePort

runtimeEgressCidr: 127.0.0.1/32

storage:
    address: 127.0.0.1
    dnsNames:
        - storage.localhost
        - longlink-storage.rustfs.svc
        - longlink-storage.rustfs.svc.cluster.local
    service:
        nodePort: 30943
        type: NodePort

rustfs:
    secret:
        existingSecret: ''
        createInsecure: true
    mode: standalone
    storage:
        name: local-path
        dataStorageSize: 1Gi
        logStorageSize: 1Gi
