gateway:
    address: ''
    service:
        annotations: {}
        loadBalancerClass: ''
        type: LoadBalancer

runtimeEgressCidr: ''

cloudnative-pg:
    fullnameOverride: cnpg-controller-manager
    namespaceOverride: cnpg-system

storage:
    address: ''
    dnsNames: []
    service:
        annotations: {}
        loadBalancerClass: ''
        nodePort: null
        type: LoadBalancer

rustfs:
    namespace: rustfs
    image:
        repository: rustfs/rustfs
        tag: 1.0.0-rc.6@sha256:97171b3d72cd47dc81000f92ea84de25608bfc35a94c965501afaeb5d99f6035
    mode: distributed
    secret:
        existingSecret: longlink-rustfs
        createInsecure: false
    storage:
        name: block-storage
        dataStorageSize: 100Gi
        logStorageSize: 1Gi
