development: false

bootstrap:
    enabled: false
    gatewayIngressCidr: ''

gateway:
    address: ''
    service:
        annotations: {}
        loadBalancerClass: ''
        type: LoadBalancer

runtimeEgressCidr: ''

storage:
    address: ''
    service:
        annotations: {}
        loadBalancerClass: ''
        nodePort: null
        type: LoadBalancer

rustfs:
    fullnameOverride: rustfs
    image:
        rustfs:
            repository: rustfs/rustfs
            tag: 1.0.0-rc.6@sha256:97171b3d72cd47dc81000f92ea84de25608bfc35a94c965501afaeb5d99f6035
    secret:
        existingSecret: longlink-rustfs
    replicaCount: 4
    drivesPerNode: 1
    storageclass:
        name: block-storage
        dataStorageSize: 100Gi
        logStorageSize: 1Gi
