image:
    repository: rustfs/rustfs
    tag: 1.0.0-rc.6

mode: distributed

secret:
    existingSecret: ''
    createInsecure: false

storage:
    name: local-path
    dataStorageSize: 256Mi
    logStorageSize: 256Mi
