apiVersion: v1
kind: ConfigMap
metadata:
    name: coredns-custom
    namespace: kube-system
data:
    storage.override: |
        rewrite stop {
           name exact storage.localhost longlink-storage-local.rustfs.svc.cluster.local
          answer auto
        }
