apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample1
  namespace: default
  labels:
    managed-by: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample1
  template:
    metadata:
      labels:
        app: sample1
    spec:
      containers:
      - name: sample1
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
        ports:
        - containerPort: 80
        command:
        - /bin/sh
        - -c
        args:
        - "\nmkdir -p /app\n\ncat <<EOF > /app/main.py\nfrom fastapi import FastAPI\n\
          \napp = FastAPI()\n\n@app.get(\"/\")\ndef root():\n    return {\"service\"\
          : \"sample1\"}\nEOF\n\nuvicorn main:app --host 0.0.0.0 --port 80\n"
---
apiVersion: v1
kind: Service
metadata:
  name: sample1
  namespace: default
  labels:
    managed-by: control-plane
spec:
  selector:
    app: sample1
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample2
  namespace: default
  labels:
    managed-by: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample2
  template:
    metadata:
      labels:
        app: sample2
    spec:
      containers:
      - name: sample2
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
        ports:
        - containerPort: 80
        command:
        - /bin/sh
        - -c
        args:
        - "\nmkdir -p /app\n\ncat <<EOF > /app/main.py\nfrom fastapi import FastAPI\n\
          \napp = FastAPI()\n\n@app.get(\"/\")\ndef root():\n    return {\"service\"\
          : \"sample2\"}\nEOF\n\nuvicorn main:app --host 0.0.0.0 --port 80\n"
---
apiVersion: v1
kind: Service
metadata:
  name: sample2
  namespace: default
  labels:
    managed-by: control-plane
spec:
  selector:
    app: sample2
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: control-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    managed-by: control-plane
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /sample1(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: sample1
            port:
              number: 80
      - path: /sample2(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: sample2
            port:
              number: 80
