name: Tests

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: api
        run: pip install -e '.[dev]'

      - name: Run tests
        working-directory: api
        run: pytest

  sdk-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.12'
          - '3.13'
          - '3.14'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        working-directory: sdk
        run: uv pip install --system -e '.[dev]'

      - name: Run tests
        working-directory: sdk
        run: uv run pytest
